<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ViajantesTurismo.ServiceDefaults\ViajantesTurismo.ServiceDefaults.csproj" />
    <ProjectReference Include="..\SharedKernel\SharedKernel.Observability.Npgsql\SharedKernel.Observability.Npgsql.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
  </ItemGroup>

  <PropertyGroup>
    <IsAotCompatible>false</IsAotCompatible>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ViajantesTurismo.DatabaseObservability.Tests" />
  </ItemGroup>

</Project>
