version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "05:00"
      timezone: "UTC"
    open-pull-requests-limit: 1
    groups:
      github-actions-minor-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      github-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
    commit-message:
      prefix: ci
      include: scope
    labels:
      - dependencies
      - ci

  - package-ecosystem: dotnet-sdk
    directory: /
    schedule:
      interval: monthly
      time: "05:00"
      timezone: "UTC"
    open-pull-requests-limit: 1
    cooldown:
      semver-major-days: 90
      semver-minor-days: 30
      semver-patch-days: 14
    groups:
      dotnet-sdk-minor-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: deps
      include: scope
    labels:
      - dependencies
      - .net

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: monthly
      time: "05:00"
      timezone: "UTC"
    open-pull-requests-limit: 1
    cooldown:
      semver-major-days: 90
      semver-minor-days: 30
      semver-patch-days: 14
    groups:
      nuget-minor-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      nuget-security:
        applies-to: security-updates
        patterns:
          - "*"
    commit-message:
      prefix: deps
      include: scope
    labels:
      - dependencies
      - .net

  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: monthly
      time: "05:00"
      timezone: "UTC"
    open-pull-requests-limit: 1
    groups:
      devcontainers:
        patterns:
          - "*"
    commit-message:
      prefix: deps
      include: scope

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      time: "05:00"
      timezone: "UTC"
    open-pull-requests-limit: 1
    cooldown:
      semver-major-days: 90
      semver-minor-days: 30
      semver-patch-days: 14
    groups:
      npm-minor-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"
    commit-message:
      prefix: deps
      include: scope
