<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <DefaultItemExcludes>$(DefaultItemExcludes);bin/**;obj/**</DefaultItemExcludes>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="bin/**/*;obj/**/*;bin\**\*;obj\**\*;$(MSBuildProjectDirectory)/bin/**/*.cs;$(MSBuildProjectDirectory)/obj/**/*.cs;$(MSBuildProjectDirectory)\bin\**\*.cs;$(MSBuildProjectDirectory)\obj\**\*.cs" />
    </ItemGroup>

    <ItemGroup>
        <None Include="OpenApi/**/*.openapi.json" Pack="true" PackagePath="OpenApi/" />
        <None Include="OpenApi/README.md" Pack="true" PackagePath="OpenApi/" />
    </ItemGroup>

</Project>
