<Project Sdk="Aspire.AppHost.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>SharedKernel.EntityFrameworkCore.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="SharedKernel.Testing.Assertions" />
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.PostgreSQL" />
        <PackageReference Include="Aspire.Hosting.Testing" />
        <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="xunit.v3.mtp-v2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.IntegrationTesting\SharedKernel.IntegrationTesting.csproj" IsAspireProjectResource="false" />
        <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.Testing\SharedKernel.Testing.csproj" IsAspireProjectResource="false" />
        <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.Testing.Assertions\SharedKernel.Testing.Assertions.csproj" IsAspireProjectResource="false" />
        <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.EntityFrameworkCore\SharedKernel.EntityFrameworkCore.csproj" IsAspireProjectResource="false" />
    </ItemGroup>

</Project>
