// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ViajantesTurismo.Admin.Infrastructure;

#nullable disable

namespace ViajantesTurismo.Admin.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ViajantesTurismo.Admin.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ViajantesTurismo.Admin.Domain.Tours.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RoomAdditionalCost")
                        .HasColumnType("numeric");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TourId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("ViajantesTurismo.Admin.Domain.Tours.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("ViajantesTurismo.Admin.Domain.Tours.Tour", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.PrimitiveCollection<string[]>("_includedServices")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("IncludedServices");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("ViajantesTurismo.Admin.Domain.Customers.Customer", b =>
                {
                    b.OwnsOne("ViajantesTurismo.Admin.Domain.Customers.AccommodationPreferences", "AccommodationPreferences", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<int>("BedType")
                                .HasColumnType("integer");

                            b1.Property<Guid?>("CompanionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("RoomType")
                                .HasColumnType("integer");

                            b1.HasKey("CustomerId");

                            b1.ToTable("CustomerAccommodationPreferences", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("ViajantesTurismo.Admin.Domain.Customers.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Complement")
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Neighborhood")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CustomerId");

                            b1.ToTable("CustomerAddress", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("ViajantesTurismo.Admin.Domain.Customers.ContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Facebook")
                                .HasColumnType("text");

                            b1.Property<string>("Instagram")
                                .HasColumnType("text");

                            b1.Property<string>("Mobile")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CustomerId");

                            b1.ToTable("CustomerContactInfo", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("ViajantesTurismo.Admin.Domain.Customers.EmergencyContact", "EmergencyContact", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Mobile")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CustomerId");

                            b1.ToTable("CustomerEmergencyContact", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("ViajantesTurismo.Admin.Domain.Customers.IdentificationInfo", "IdentificationInfo", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("IdNationality")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("NationalId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CustomerId");

                            b1.ToTable("CustomerIdentificationInfo", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("ViajantesTurismo.Admin.Domain.Customers.MedicalInfo", "MedicalInfo", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AdditionalInfo")
                                .HasColumnType("text");

                            b1.Property<string>("Allergies")
                                .HasColumnType("text");

                            b1.HasKey("CustomerId");

                            b1.ToTable("CustomerMedicalInfo", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("ViajantesTurismo.Admin.Domain.Customers.PersonalInfo", "PersonalInfo", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("BirthDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Gender")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Nationality")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Profession")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CustomerId");

                            b1.ToTable("CustomerPersonalInfo", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("ViajantesTurismo.Admin.Domain.Customers.PhysicalInfo", "PhysicalInfo", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<int>("BikeType")
                                .HasColumnType("integer");

                            b1.Property<int>("HeightCentimeters")
                                .HasColumnType("integer");

                            b1.Property<decimal>("WeightKg")
                                .HasColumnType("numeric");

                            b1.HasKey("CustomerId");

                            b1.ToTable("CustomerPhysicalInfo", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.Navigation("AccommodationPreferences")
                        .IsRequired();

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("ContactInfo")
                        .IsRequired();

                    b.Navigation("EmergencyContact")
                        .IsRequired();

                    b.Navigation("IdentificationInfo")
                        .IsRequired();

                    b.Navigation("MedicalInfo")
                        .IsRequired();

                    b.Navigation("PersonalInfo")
                        .IsRequired();

                    b.Navigation("PhysicalInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("ViajantesTurismo.Admin.Domain.Tours.Booking", b =>
                {
                    b.HasOne("ViajantesTurismo.Admin.Domain.Tours.Tour", null)
                        .WithMany("Bookings")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ViajantesTurismo.Admin.Domain.Tours.BookingCustomer", "CompanionCustomer", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("BikePrice")
                                .HasColumnType("numeric");

                            b1.Property<string>("BikeType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.HasKey("BookingId");

                            b1.HasIndex("CustomerId");

                            b1.ToTable("Booking");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");

                            b1.HasOne("ViajantesTurismo.Admin.Domain.Customers.Customer", null)
                                .WithMany()
                                .HasForeignKey("CustomerId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();
                        });

                    b.OwnsOne("ViajantesTurismo.Admin.Domain.Tours.BookingCustomer", "PrincipalCustomer", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("BikePrice")
                                .HasColumnType("numeric");

                            b1.Property<string>("BikeType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.HasKey("BookingId");

                            b1.HasIndex("CustomerId");

                            b1.ToTable("Booking");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");

                            b1.HasOne("ViajantesTurismo.Admin.Domain.Customers.Customer", null)
                                .WithMany()
                                .HasForeignKey("CustomerId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();
                        });

                    b.OwnsOne("ViajantesTurismo.Admin.Domain.Tours.Discount", "Discount", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<string>("Reason")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("BookingId");

                            b1.ToTable("Booking");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.Navigation("CompanionCustomer");

                    b.Navigation("Discount")
                        .IsRequired();

                    b.Navigation("PrincipalCustomer")
                        .IsRequired();
                });

            modelBuilder.Entity("ViajantesTurismo.Admin.Domain.Tours.Payment", b =>
                {
                    b.HasOne("ViajantesTurismo.Admin.Domain.Tours.Booking", null)
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ViajantesTurismo.Admin.Domain.Tours.Tour", b =>
                {
                    b.OwnsOne("ViajantesTurismo.Admin.Domain.Tours.TourCapacity", "Capacity", b1 =>
                        {
                            b1.Property<Guid>("TourId")
                                .HasColumnType("uuid");

                            b1.Property<int>("MaxCustomers")
                                .HasColumnType("integer")
                                .HasColumnName("MaxCustomers");

                            b1.Property<int>("MinCustomers")
                                .HasColumnType("integer")
                                .HasColumnName("MinCustomers");

                            b1.HasKey("TourId");

                            b1.ToTable("Tours");

                            b1.WithOwner()
                                .HasForeignKey("TourId");
                        });

                    b.OwnsOne("ViajantesTurismo.Admin.Domain.Tours.TourPricing", "Pricing", b1 =>
                        {
                            b1.Property<Guid>("TourId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("BasePrice")
                                .HasColumnType("numeric")
                                .HasColumnName("Price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Currency");

                            b1.Property<decimal>("DoubleRoomSupplementPrice")
                                .HasColumnType("numeric")
                                .HasColumnName("DoubleRoomSupplementPrice");

                            b1.Property<decimal>("EBikePrice")
                                .HasColumnType("numeric")
                                .HasColumnName("EBikePrice");

                            b1.Property<decimal>("RegularBikePrice")
                                .HasColumnType("numeric")
                                .HasColumnName("RegularBikePrice");

                            b1.HasKey("TourId");

                            b1.ToTable("Tours");

                            b1.WithOwner()
                                .HasForeignKey("TourId");
                        });

                    b.OwnsOne("ViajantesTurismo.Common.BuildingBlocks.DateRange", "Schedule", b1 =>
                        {
                            b1.Property<Guid>("TourId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("EndDate");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("StartDate");

                            b1.HasKey("TourId");

                            b1.ToTable("Tours");

                            b1.WithOwner()
                                .HasForeignKey("TourId");
                        });

                    b.Navigation("Capacity")
                        .IsRequired();

                    b.Navigation("Pricing")
                        .IsRequired();

                    b.Navigation("Schedule")
                        .IsRequired();
                });

            modelBuilder.Entity("ViajantesTurismo.Admin.Domain.Tours.Booking", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ViajantesTurismo.Admin.Domain.Tours.Tour", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
