using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SharedKernel.Messaging.IntegrationEvents.SourceGenerator;

/// <summary>
/// Generates domain event dispatching for attributed integration event mapping methods.
/// </summary>
[Generator]
public sealed class IntegrationEventMappingGenerator : IIncrementalGenerator
{
    private const string AttributeName = "SharedKernel.Messaging.IntegrationEvents.IntegrationEventMappingAttribute";
    private const string DomainEventInterfaceName = "SharedKernel.Domain.IDomainEvent";
    private const string IntegrationEventInterfaceName = "SharedKernel.Messaging.IntegrationEvents.IIntegrationEvent";

    private static readonly SymbolDisplayFormat FullyQualifiedFormat = new(
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var mappings = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeName,
                static (node, _) => node is MethodDeclarationSyntax,
                static (attributeContext, cancellationToken) => BuildMapping(attributeContext, cancellationToken))
            .Where(static mapping => mapping is not null)
            .Collect()
            .Select(static (mappings, _) => mappings
                .Where(static mapping => mapping is not null)
                .Select(static mapping => mapping!)
                .OrderBy(static mapping => mapping.DomainEventType, StringComparer.Ordinal)
                .ThenBy(static mapping => mapping.IntegrationEventType, StringComparer.Ordinal)
                .ToImmutableArray())
            .WithTrackingName("IntegrationEventMappings");

        context.RegisterSourceOutput(mappings, static (productionContext, mappings) =>
        {
            if (mappings.Length == 0)
            {
                return;
            }

            productionContext.AddSource(
                "SharedKernel.Messaging.IntegrationEvents.GeneratedIntegrationEventMappings.g.cs",
                SourceText.From(Emit(mappings), Encoding.UTF8));
        });
    }

    private static IntegrationEventMappingModel? BuildMapping(
        GeneratorAttributeSyntaxContext context,
        CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        var method = (IMethodSymbol)context.TargetSymbol;
        if (method.IsGenericMethod || !method.IsStatic || !IsAccessibleToGeneratedCode(method) || method.Parameters.Length != 3)
        {
            return null;
        }

        var domainEvent = method.Parameters[0].Type;
        var integrationEvent = method.ReturnType;
        if (!Implements(domainEvent, DomainEventInterfaceName) || !Implements(integrationEvent, IntegrationEventInterfaceName))
        {
            return null;
        }

        if (method.Parameters[1].Type.ToDisplayString() != "System.Guid" ||
            method.Parameters[2].Type.ToDisplayString() != "System.DateTimeOffset")
        {
            return null;
        }

        var containingType = method.ContainingType.ToDisplayString(FullyQualifiedFormat);
        var domainEventType = domainEvent.ToDisplayString(FullyQualifiedFormat);
        var integrationEventType = integrationEvent.ToDisplayString(FullyQualifiedFormat);
        var dispatchMethodName = $"Dispatch{Sanitize(domainEvent.ToDisplayString())}";

        return new IntegrationEventMappingModel(
            containingType,
            method.Name,
            domainEventType,
            integrationEventType,
            dispatchMethodName);
    }

    private static bool Implements(ITypeSymbol type, string interfaceName)
    {
        return string.Equals(type.OriginalDefinition.ToDisplayString(), interfaceName, StringComparison.Ordinal) ||
            type.AllInterfaces.Any(interfaceType =>
            string.Equals(interfaceType.OriginalDefinition.ToDisplayString(), interfaceName, StringComparison.Ordinal));
    }

    private static bool IsAccessibleToGeneratedCode(IMethodSymbol method) =>
        method.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal;

    private static string Emit(ImmutableArray<IntegrationEventMappingModel> mappings)
    {
        var builder = new StringBuilder(
            """
            // <auto-generated />
            #nullable enable

            namespace SharedKernel.Messaging.IntegrationEvents.Generated
            {

            """);

        builder.AppendLine($$"""
            internal sealed class GeneratedIntegrationEventDomainEventDispatcher(
                global::SharedKernel.Messaging.IntegrationEvents.IIntegrationEventOutbox outbox,
                global::System.TimeProvider timeProvider)
                : global::SharedKernel.DomainEvents.IDomainEventDispatcher
            {
                public global::System.Threading.Tasks.ValueTask Dispatch<TDomainEvent>(TDomainEvent domainEvent, global::System.Threading.CancellationToken ct)
                    where TDomainEvent : global::SharedKernel.Domain.IDomainEvent
                {
                    global::System.ArgumentNullException.ThrowIfNull(domainEvent);

                    return Dispatch((global::SharedKernel.Domain.IDomainEvent)domainEvent, ct);
                }

                public global::System.Threading.Tasks.ValueTask Dispatch(global::SharedKernel.Domain.IDomainEvent domainEvent, global::System.Threading.CancellationToken ct)
                {
                    global::System.ArgumentNullException.ThrowIfNull(domainEvent);

                    return domainEvent switch
                    {

            """);

        foreach (var domainEventType in mappings.Select(static mapping => mapping.DomainEventType).Distinct(StringComparer.Ordinal))
        {
            var dispatchMethodName = mappings.First(mapping => string.Equals(mapping.DomainEventType, domainEventType, StringComparison.Ordinal)).DispatchMethodName;
            builder.AppendLine($"            {domainEventType} typedDomainEvent => {dispatchMethodName}(typedDomainEvent, ct),");
        }

        builder.AppendLine("            _ => global::System.Threading.Tasks.ValueTask.CompletedTask,");
        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine();

        foreach (var group in mappings.GroupBy(static mapping => mapping.DomainEventType).OrderBy(static group => group.Key, StringComparer.Ordinal))
        {
            var firstMapping = group.First();
            builder.AppendLine($"    private async global::System.Threading.Tasks.ValueTask {firstMapping.DispatchMethodName}({group.Key} domainEvent, global::System.Threading.CancellationToken ct)");
            builder.AppendLine("    {");

            foreach (var mapping in group.OrderBy(static mapping => mapping.IntegrationEventType, StringComparer.Ordinal))
            {
                builder.AppendLine("        await outbox.Enqueue(");
                builder.AppendLine($"            {mapping.ContainingType}.{mapping.MethodName}(");
                builder.AppendLine("                domainEvent,");
                builder.AppendLine("                global::System.Guid.CreateVersion7(),");
                builder.AppendLine("                timeProvider.GetUtcNow()),");
                builder.AppendLine("            ct).ConfigureAwait(false);");
            }

            builder.AppendLine("    }");
            builder.AppendLine();
        }

        builder.AppendLine("}");

        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("namespace Microsoft.Extensions.DependencyInjection");
        builder.AppendLine("{");
        builder.AppendLine();
        builder.AppendLine("internal static class GeneratedIntegrationEventMappingsServiceCollectionExtensions");
        builder.AppendLine("{");
        builder.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedIntegrationEventMappings(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(services);");
        builder.AppendLine("        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton(services, global::System.TimeProvider.System);");
        builder.AppendLine("        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped<global::SharedKernel.DomainEvents.IDomainEventDispatcher, global::SharedKernel.Messaging.IntegrationEvents.Generated.GeneratedIntegrationEventDomainEventDispatcher>(services);");

        builder.AppendLine("        return services;");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static string Sanitize(string value)
    {
        var builder = new StringBuilder();
        foreach (var character in value.Where(char.IsLetterOrDigit))
        {
            builder.Append(character);
        }

        return builder.ToString();
    }
}

internal sealed class IntegrationEventMappingModel(
    string containingType,
    string methodName,
    string domainEventType,
    string integrationEventType,
    string dispatchMethodName)
{
    public string ContainingType { get; } = containingType;

    public string MethodName { get; } = methodName;

    public string DomainEventType { get; } = domainEventType;

    public string IntegrationEventType { get; } = integrationEventType;

    public string DispatchMethodName { get; } = dispatchMethodName;
}
