<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <!-- EF Core DbContext is not Native AOT-compatible. -->
        <IsAotCompatible>false</IsAotCompatible>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="ViajantesTurismo.Branding.ApiServiceTests" />
        <InternalsVisibleTo Include="ViajantesTurismo.Admin.IntegrationTests" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Npgsql" />
        <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SharedKernel\SharedKernel.Branding\SharedKernel.Branding.csproj" />
        <ProjectReference Include="..\SharedKernel\SharedKernel.EntityFrameworkCore\SharedKernel.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\ViajantesTurismo.Resources\ViajantesTurismo.Resources.csproj" />
    </ItemGroup>

</Project>
