<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>ViajantesTurismo.Public.WebTests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="System.Net" />
        <Using Include="SharedKernel.Branding" />
        <Using Include="SharedKernel.Testing" />
        <Using Include="SharedKernel.Testing.Assertions" />
        <Using Include="SharedKernel.Testing.AspNetCore" />
        <Using Include="ViajantesTurismo.Catalog.Contracts.Application" />
        <Using Include="ViajantesTurismo.Catalog.Contracts.Http" />
        <Using Include="ViajantesTurismo.Public.Web" />
        <Using Include="ViajantesTurismo.Public.WebTests.Infrastructure" />
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="bunit" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="xunit.v3.mtp-v2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\ViajantesTurismo.Public.Web\ViajantesTurismo.Public.Web.csproj" />
        <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.Testing.AspNetCore\SharedKernel.Testing.AspNetCore.csproj" />
        <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.Testing\SharedKernel.Testing.csproj" />
        <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.Testing.Assertions\SharedKernel.Testing.Assertions.csproj" />
    </ItemGroup>

</Project>
