using System.Text;

namespace SharedKernel.Mediator.SourceGenerator;

/// <summary>
/// Emits generated telemetry constants for mediator dispatch.
/// </summary>
internal static class AppMediatorTelemetryEmitter
{
    public static string Emit()
    {
        var builder = new StringBuilder();
        GeneratedXmlDocumentationEmitter.AppendAutoGeneratedHeader(builder);
        builder.AppendLine("namespace SharedKernel.Mediator;");
        builder.AppendLine();
        builder.AppendLine("internal static class AppMediatorTelemetry");
        builder.AppendLine("{");
        builder.AppendLine("    internal const string ActivitySourceName = \"SharedKernel.Mediator\";");
        builder.AppendLine("    internal const string MeterName = \"SharedKernel.Mediator\";");
        builder.AppendLine("    internal const string SendSpanName = \"mediator.send\";");
        builder.AppendLine("    internal const string StreamSpanName = \"mediator.stream\";");
        builder.AppendLine("    internal const string PublishSpanName = \"mediator.publish\";");
        builder.AppendLine("    internal const string HandlerSpanName = \"mediator.notification.handle\";");
        builder.AppendLine("}");
        return builder.ToString();
    }
}
