using System.Text;

namespace SharedKernel.Mediator.SourceGenerator;

/// <summary>
/// Emits generated telemetry constants for mediator dispatch.
/// </summary>
internal static class AppMediatorTelemetryEmitter
{
    public static string Emit()
    {
        var builder = new StringBuilder();
        GeneratedXmlDocumentationEmitter.AppendAutoGeneratedHeader(builder);
        builder.AppendLine("namespace SharedKernel.Mediator;");
        builder.AppendLine();
        builder.AppendLine("internal static class AppMediatorTelemetry");
        builder.AppendLine("{");
        builder.AppendLine("    internal static string ActivitySourceName => global::SharedKernel.Mediator.MediatorTelemetry.Name;");
        builder.AppendLine("    internal static string MeterName => global::SharedKernel.Mediator.MediatorTelemetry.Name;");
        builder.AppendLine("    internal static string SendSpanName => global::SharedKernel.Mediator.MediatorTelemetry.ActivitySend;");
        builder.AppendLine("    internal static string StreamSpanName => global::SharedKernel.Mediator.MediatorTelemetry.ActivityStream;");
        builder.AppendLine("    internal static string PublishSpanName => global::SharedKernel.Mediator.MediatorTelemetry.ActivityPublish;");
        builder.AppendLine("    internal static string HandlerSpanName => global::SharedKernel.Mediator.MediatorTelemetry.ActivityNotificationHandler;");
        builder.AppendLine("}");
        return builder.ToString();
    }
}
