using System.Text;
using System.Text.RegularExpressions;

namespace SharedKernel.Documentation;

/// <summary>
/// Updates named generated blocks inside Markdown documents.
/// </summary>
internal sealed class GeneratedMarkdownUpdater(string rootPath, string docsRelativePath, string generatorName)
{
    private static readonly UTF8Encoding Utf8NoBom = new(false);

    /// <summary>
    /// Updates generated blocks and returns repository-relative files whose content changed.
    /// </summary>
    /// <param name="checkOnly">Whether to detect drift without writing files.</param>
    /// <param name="replacements">Generated block names and replacement content.</param>
    /// <returns>Repository-relative file paths changed or stale.</returns>
    public List<string> Update(bool checkOnly, Dictionary<string, string> replacements)
    {
        ArgumentNullException.ThrowIfNull(replacements);

        var changed = new List<string>();
        foreach (var path in MarkdownDocs().Select(file => file.FullName))
        {
            var original = File.ReadAllText(path, Utf8NoBom);
            var updated = UpdateText(original, replacements);
            if (updated == original)
            {
                continue;
            }

            changed.Add(Path.GetRelativePath(rootPath, path).Replace(Path.DirectorySeparatorChar, '/'));
            if (!checkOnly)
            {
                File.WriteAllText(path, updated, Utf8NoBom);
            }
        }

        return changed;
    }

    private IEnumerable<FileInfo> MarkdownDocs() =>
        new DirectoryInfo(Path.Combine(rootPath, docsRelativePath))
            .EnumerateFiles("*.md")
            .OrderBy(file => file.FullName, StringComparer.Ordinal);

    private string UpdateText(string text, Dictionary<string, string> replacements)
    {
        foreach (var (name, replacement) in replacements)
        {
            text = ReplaceGeneratedBlock(text, name, replacement);
        }

        return text;
    }

    private string ReplaceGeneratedBlock(string text, string name, string replacement)
    {
        var pattern = new Regex($"<!-- generated:{Regex.Escape(name)}:start -->.*?<!-- generated:{Regex.Escape(name)}:end -->", RegexOptions.Singleline | RegexOptions.CultureInvariant);
        var block = string.Join(
            '\n',
            $"<!-- generated:{name}:start -->",
            $"<!-- Generated by {generatorName}. Do not edit by hand. -->",
            string.Empty,
            replacement.TrimEnd(),
            $"<!-- generated:{name}:end -->");

        return pattern.Replace(text, block);
    }
}
