<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <None Include="OpenApi/**/*.openapi.json" Pack="true" PackagePath="OpenApi/" />
        <None Include="OpenApi/README.md" Pack="true" PackagePath="OpenApi/" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SharedKernel\SharedKernel.HttpClients\SharedKernel.HttpClients.csproj" />
        <ProjectReference Include="..\SharedKernel\SharedKernel.Messaging.IntegrationEvents\SharedKernel.Messaging.IntegrationEvents.csproj" />
    </ItemGroup>

</Project>
