// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using ViajantesTurismo.Admin.Infrastructure;
using ViajantesTurismo.Admin.Infrastructure.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(AdminWriteDbContext), typeof(AdminWriteDbContextModel))]
