// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace ViajantesTurismo.Admin.Infrastructure.CompiledModels
{
    public partial class AdminWriteDbContextModel
    {
        private AdminWriteDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("7d1e6a4a-e699-4c5b-bd1d-efe7fcc5fa8e"), entityTypeCount: 18)
        {
        }

        partial void Initialize()
        {
            var accommodationPreferences = AccommodationPreferencesEntityType.Create(this);
            var address = AddressEntityType.Create(this);
            var contactInfo = ContactInfoEntityType.Create(this);
            var customer = CustomerEntityType.Create(this);
            var emergencyContact = EmergencyContactEntityType.Create(this);
            var identificationInfo = IdentificationInfoEntityType.Create(this);
            var medicalInfo = MedicalInfoEntityType.Create(this);
            var personalInfo = PersonalInfoEntityType.Create(this);
            var physicalInfo = PhysicalInfoEntityType.Create(this);
            var booking = BookingEntityType.Create(this);
            var bookingCustomer = BookingCustomerEntityType.Create(this);
            var bookingCustomer0 = BookingCustomer0EntityType.Create(this);
            var discount = DiscountEntityType.Create(this);
            var payment = PaymentEntityType.Create(this);
            var tour = TourEntityType.Create(this);
            var tourCapacity = TourCapacityEntityType.Create(this);
            var tourPricing = TourPricingEntityType.Create(this);
            var dateRange = DateRangeEntityType.Create(this);

            AccommodationPreferencesEntityType.CreateForeignKey1(accommodationPreferences, customer);
            AddressEntityType.CreateForeignKey1(address, customer);
            ContactInfoEntityType.CreateForeignKey1(contactInfo, customer);
            EmergencyContactEntityType.CreateForeignKey1(emergencyContact, customer);
            IdentificationInfoEntityType.CreateForeignKey1(identificationInfo, customer);
            MedicalInfoEntityType.CreateForeignKey1(medicalInfo, customer);
            PersonalInfoEntityType.CreateForeignKey1(personalInfo, customer);
            PhysicalInfoEntityType.CreateForeignKey1(physicalInfo, customer);
            BookingEntityType.CreateForeignKey1(booking, tour);
            BookingCustomerEntityType.CreateForeignKey1(bookingCustomer, booking);
            BookingCustomer0EntityType.CreateForeignKey1(bookingCustomer0, booking);
            DiscountEntityType.CreateForeignKey1(discount, booking);
            PaymentEntityType.CreateForeignKey1(payment, booking);
            TourCapacityEntityType.CreateForeignKey1(tourCapacity, tour);
            TourPricingEntityType.CreateForeignKey1(tourPricing, tour);
            DateRangeEntityType.CreateForeignKey1(dateRange, tour);

            AccommodationPreferencesEntityType.CreateAnnotations(accommodationPreferences);
            AddressEntityType.CreateAnnotations(address);
            ContactInfoEntityType.CreateAnnotations(contactInfo);
            CustomerEntityType.CreateAnnotations(customer);
            EmergencyContactEntityType.CreateAnnotations(emergencyContact);
            IdentificationInfoEntityType.CreateAnnotations(identificationInfo);
            MedicalInfoEntityType.CreateAnnotations(medicalInfo);
            PersonalInfoEntityType.CreateAnnotations(personalInfo);
            PhysicalInfoEntityType.CreateAnnotations(physicalInfo);
            BookingEntityType.CreateAnnotations(booking);
            BookingCustomerEntityType.CreateAnnotations(bookingCustomer);
            BookingCustomer0EntityType.CreateAnnotations(bookingCustomer0);
            DiscountEntityType.CreateAnnotations(discount);
            PaymentEntityType.CreateAnnotations(payment);
            TourEntityType.CreateAnnotations(tour);
            TourCapacityEntityType.CreateAnnotations(tourCapacity);
            TourPricingEntityType.CreateAnnotations(tourPricing);
            DateRangeEntityType.CreateAnnotations(dateRange);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "10.0.0");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
