// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ViajantesTurismo.Admin.Domain.Tours;

#pragma warning disable 219, 612, 618
#nullable disable

namespace ViajantesTurismo.Admin.Infrastructure.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class TourCapacityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "ViajantesTurismo.Admin.Domain.Tours.TourCapacity",
                typeof(TourCapacity),
                baseEntityType,
                propertyCount: 3,
                foreignKeyCount: 1,
                keyCount: 1);

            var tourId = runtimeEntityType.AddProperty(
                "TourId",
                typeof(Guid),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            tourId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var maxCustomers = runtimeEntityType.AddProperty(
                "MaxCustomers",
                typeof(int),
                propertyInfo: typeof(TourCapacity).GetProperty("MaxCustomers", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TourCapacity).GetField("<MaxCustomers>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            maxCustomers.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            maxCustomers.AddAnnotation("Relational:ColumnName", "MaxCustomers");

            var minCustomers = runtimeEntityType.AddProperty(
                "MinCustomers",
                typeof(int),
                propertyInfo: typeof(TourCapacity).GetProperty("MinCustomers", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TourCapacity).GetField("<MinCustomers>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            minCustomers.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            minCustomers.AddAnnotation("Relational:ColumnName", "MinCustomers");

            var key = runtimeEntityType.AddKey(
                new[] { tourId });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("TourId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                unique: true,
                required: true,
                requiredDependent: true,
                ownership: true);

            var capacity = principalEntityType.AddNavigation("Capacity",
                runtimeForeignKey,
                onDependent: false,
                typeof(TourCapacity),
                propertyInfo: typeof(Tour).GetProperty("Capacity", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Tour).GetField("<Capacity>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                eagerLoaded: true);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Tours");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
