// <auto-generated />
#nullable enable

namespace SharedKernel.Mediator;

internal static class GeneratedPipelines
{

    public static global::System.Threading.Tasks.ValueTask<int> Invoke_0000(AppMediator mediator, global::Demo.CreateTour request,
        global::System.Threading.CancellationToken ct)
    {
        var pipeline0 = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.ValidationBehavior>(mediator.Services);
        var handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.CreateTourHandler>(mediator.Services);

        return pipeline0.Handle(request, () => handler.Handle(request, ct), ct);
    }
}
