// <auto-generated />
#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace SharedKernel.Mediator;

/// <summary>
/// Provides the generated dependency injection registrations for mediator services.
/// </summary>
public static partial class SharedKernelMediatorServiceCollectionExtensions
{
    /// <summary>
    /// Adds the generated mediator registrations to the service collection.
    /// </summary>
    /// <param name="services">The service collection to populate.</param>
    /// <returns>The same service collection so calls can be chained.</returns>
    public static IServiceCollection AddSharedKernelMediator(this IServiceCollection services)
    {
        global::System.ArgumentNullException.ThrowIfNull(services);
        services.AddMetrics();
        services.AddSingleton<AppMediatorInstrumentation>();
        services.AddScoped<AppMediator>();
        services.AddScoped<ISender>(static sp => sp.GetRequiredService<AppMediator>());
        services.AddScoped<IPublisher>(static sp => sp.GetRequiredService<AppMediator>());
        services.AddScoped<IMediator>(static sp => sp.GetRequiredService<AppMediator>());

        services.AddScoped<global::Demo.CreateTourHandler>();
        services.AddScoped<global::System.Func<global::Demo.CreateTourHandler>>(static sp => () => sp.GetRequiredService<global::Demo.CreateTourHandler>());
        services.AddScoped<global::Demo.ValidationBehavior>();
        services.AddScoped<global::System.Func<global::Demo.ValidationBehavior>>(static sp => () => sp.GetRequiredService<global::Demo.ValidationBehavior>());

        services.AddScoped<global::Demo.TourCreatedHandler>();
        services.AddScoped<global::System.Func<global::Demo.TourCreatedHandler>>(static sp => () => sp.GetRequiredService<global::Demo.TourCreatedHandler>());

        services.AddScoped<global::Demo.StreamToursHandler>();
        services.AddScoped<global::System.Func<global::Demo.StreamToursHandler>>(static sp => () => sp.GetRequiredService<global::Demo.StreamToursHandler>());

        return services;
    }
}
