// <auto-generated />

namespace SharedKernel.Mediator;

public sealed partial class AppMediator : IMediator
{
    public AppMediator(global::System.IServiceProvider services)
    {
        global::System.ArgumentNullException.ThrowIfNull(services);

        Services = services;
    }

    internal global::System.IServiceProvider Services { get; }

    public global::System.Threading.Tasks.ValueTask<TResponse> Send<TResponse>(
        global::SharedKernel.Mediator.IRequest<TResponse> request,
        global::System.Threading.CancellationToken ct)
    {
        global::System.ArgumentNullException.ThrowIfNull(request);

        throw new global::System.NotSupportedException("Generated request dispatch is not available yet.");
    }

    public global::System.Threading.Tasks.ValueTask Publish<TNotification>(
        TNotification notification,
        global::System.Threading.CancellationToken ct)
        where TNotification : global::SharedKernel.Mediator.INotification
    {
        global::System.ArgumentNullException.ThrowIfNull(notification);

        throw new global::System.NotSupportedException("Generated notification dispatch is not available yet.");
    }
}
