// <auto-generated />
#nullable enable

namespace SharedKernel.Mediator;

internal static class GeneratedDispatch
{
    public static global::System.Threading.Tasks.ValueTask<TResponse> Send<TResponse>(
        AppMediator mediator,
        global::SharedKernel.Mediator.IRequest<TResponse> request,
        global::System.Threading.CancellationToken ct)
    {
        return request switch
        {
            _ => ThrowNoHandler<TResponse>(request),
        };
    }

    public static global::System.Threading.Tasks.ValueTask<object?> SendObject(
        AppMediator mediator,
        object request,
        global::System.Threading.CancellationToken ct)
    {
        return request switch
        {
            _ => ThrowUnknownRequestObject(request),
        };
    }

    public static global::System.Threading.Tasks.ValueTask Publish<TNotification>(
        AppMediator mediator,
        TNotification notification,
        global::System.Threading.CancellationToken ct)
        where TNotification : global::SharedKernel.Mediator.INotification
    {
        return notification switch
        {
            global::Demo.TourCreated typed => Publish_0000(mediator.Services, typed, ct),
            _ => global::System.Threading.Tasks.ValueTask.CompletedTask,
        };
    }

    private static async global::System.Threading.Tasks.ValueTask Publish_0000(
        global::System.IServiceProvider services,
        global::Demo.TourCreated notification,
        global::System.Threading.CancellationToken ct)
    {
        var handler0 = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.TourCreatedHandlerOne>(services).Handle(notification, ct);
        var handler1 = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.TourCreatedHandlerTwo>(services).Handle(notification, ct);
        await global::System.Threading.Tasks.Task.WhenAll(handler0.AsTask(), handler1.AsTask()).ConfigureAwait(false);
    }

    public static async global::System.Threading.Tasks.ValueTask<TTarget> Cast<TSource, TTarget>(
        global::System.Threading.Tasks.ValueTask<TSource> source)
    {
        var result = await source.ConfigureAwait(false);

        if (result is TTarget typed)
        {
            return typed;
        }

        return ThrowInvalidResponseCast<TSource, TTarget>();
    }

    public static async global::System.Threading.Tasks.ValueTask<object?> Box<TSource>(
        global::System.Threading.Tasks.ValueTask<TSource> source)
    {
        return await source.ConfigureAwait(false);
    }

    public static global::System.Threading.Tasks.ValueTask<TResponse> ThrowNoHandler<TResponse>(
        global::SharedKernel.Mediator.IRequest<TResponse> request)
    {
        global::System.ArgumentNullException.ThrowIfNull(request);

        throw new global::System.NotSupportedException($"Generated request dispatch is not available for request type '{request.GetType().FullName}'.");
    }

    public static global::System.Threading.Tasks.ValueTask<object?> ThrowUnknownRequestObject(
        object request)
    {
        global::System.ArgumentNullException.ThrowIfNull(request);

        throw new global::System.NotSupportedException($"Generated object dispatch is not available for request type '{request.GetType().FullName}'.");
    }

    public static global::System.Threading.Tasks.ValueTask<TResponse> ThrowAmbiguousHandlers<TResponse>(
        global::SharedKernel.Mediator.IRequest<TResponse> request,
        int handlerCount)
    {
        global::System.ArgumentNullException.ThrowIfNull(request);

        throw new global::System.InvalidOperationException($"Generated request dispatch found {handlerCount} accessible handlers for request type '{request.GetType().FullName}'.");
    }

    public static TTarget ThrowInvalidResponseCast<TSource, TTarget>()
    {
        throw new global::System.InvalidOperationException($"Generated request dispatch returned '{typeof(TSource).FullName}' when '{typeof(TTarget).FullName}' was expected.");
    }
}
