// <auto-generated />
#nullable enable

namespace SharedKernel.Mediator;

/// <summary>
/// Provides the generated mediator shell owned by the consumer compilation.
/// </summary>
public sealed partial class AppMediator : IMediator
{
    private readonly global::SharedKernel.Mediator.AppMediatorInstrumentation _instrumentation;

    /// <summary>
    /// Initializes a new instance of the <see cref="AppMediator"/> class.
    /// </summary>
    /// <param name="services">The scoped service provider used by generated mediator code.</param>
    public AppMediator(global::System.IServiceProvider services)
    {
        global::System.ArgumentNullException.ThrowIfNull(services);

        Services = services;
        _instrumentation = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::SharedKernel.Mediator.AppMediatorInstrumentation>(services);
    }

    /// <summary>
    /// Gets the scoped service provider used by generated mediator code.
    /// </summary>
    internal global::System.IServiceProvider Services { get; }

    /// <summary>
    /// Gets the instrumentation services used by generated mediator code.
    /// </summary>
    internal global::SharedKernel.Mediator.AppMediatorInstrumentation Instrumentation => _instrumentation;


    /// <summary>
    /// Sends a <see cref="global::Demo.CreateTour"/> request through the generated mediator dispatch path.
    /// </summary>
    /// <param name="request">The request instance to dispatch.</param>
    /// <param name="ct">The cancellation token for the operation.</param>
    /// <returns>The produced response value.</returns>
    public async global::System.Threading.Tasks.ValueTask<int> Send(global::Demo.CreateTour request,
        global::System.Threading.CancellationToken ct)
    {
        global::System.ArgumentNullException.ThrowIfNull(request);

        var activity = _instrumentation.ActivitySource.StartActivity("mediator.send", global::System.Diagnostics.ActivityKind.Internal);
        activity?.SetTag("mediator.request.name", "CreateTour");
        activity?.SetTag("mediator.request.assembly", "SharedKernel.Mediator.Tests.Dynamic");
        activity?.SetTag("mediator.handler.name", "CreateTourHandler");
        activity?.SetTag("mediator.pipeline.depth", 0);
        var sw = global::System.Diagnostics.Stopwatch.GetTimestamp();
        var outcome = "success";
        try
        {
            var handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.CreateTourHandler>(Services);

            var result = await handler.Handle(request, ct).ConfigureAwait(false);
            activity?.SetTag("mediator.outcome", "success");
            activity?.SetStatus(global::System.Diagnostics.ActivityStatusCode.Ok);
            return result;
        }
        catch (global::System.OperationCanceledException)
        {
            outcome = "cancelled";
            activity?.SetTag("mediator.outcome", "cancelled");
            throw;
        }
        catch (global::System.Exception ex)
        {
            outcome = "error";
            activity?.SetTag("error.type", ex.GetType().Name);
            activity?.AddException(ex);
            activity?.SetStatus(global::System.Diagnostics.ActivityStatusCode.Error, ex.Message);
            activity?.SetTag("mediator.outcome", "error");
            throw;
        }
        finally
        {
            activity?.Dispose();
            _instrumentation.RequestsTotal.Add(1, new global::System.Diagnostics.TagList { { "mediator.request.name", "CreateTour" }, { "mediator.outcome", outcome } });
            _instrumentation.RequestsDuration.Record(global::System.Diagnostics.Stopwatch.GetElapsedTime(sw).TotalMilliseconds, new global::System.Diagnostics.TagList { { "mediator.request.name", "CreateTour" }, { "mediator.outcome", outcome } });
        }
    }

    /// <summary>
    /// Sends a <see cref="global::Demo.DeleteTour"/> request through the generated mediator dispatch path.
    /// </summary>
    /// <param name="request">The request instance to dispatch.</param>
    /// <param name="ct">The cancellation token for the operation.</param>
    /// <returns>The produced response value.</returns>
    public async global::System.Threading.Tasks.ValueTask<global::SharedKernel.Mediator.Unit> Send(global::Demo.DeleteTour request,
        global::System.Threading.CancellationToken ct)
    {
        global::System.ArgumentNullException.ThrowIfNull(request);

        var activity = _instrumentation.ActivitySource.StartActivity("mediator.send", global::System.Diagnostics.ActivityKind.Internal);
        activity?.SetTag("mediator.request.name", "DeleteTour");
        activity?.SetTag("mediator.request.assembly", "SharedKernel.Mediator.Tests.Dynamic");
        activity?.SetTag("mediator.handler.name", "DeleteTourHandler");
        activity?.SetTag("mediator.pipeline.depth", 0);
        var sw = global::System.Diagnostics.Stopwatch.GetTimestamp();
        var outcome = "success";
        try
        {
            var handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.DeleteTourHandler>(Services);

            var result = await handler.Handle(request, ct).ConfigureAwait(false);
            activity?.SetTag("mediator.outcome", "success");
            activity?.SetStatus(global::System.Diagnostics.ActivityStatusCode.Ok);
            return result;
        }
        catch (global::System.OperationCanceledException)
        {
            outcome = "cancelled";
            activity?.SetTag("mediator.outcome", "cancelled");
            throw;
        }
        catch (global::System.Exception ex)
        {
            outcome = "error";
            activity?.SetTag("error.type", ex.GetType().Name);
            activity?.AddException(ex);
            activity?.SetStatus(global::System.Diagnostics.ActivityStatusCode.Error, ex.Message);
            activity?.SetTag("mediator.outcome", "error");
            throw;
        }
        finally
        {
            activity?.Dispose();
            _instrumentation.RequestsTotal.Add(1, new global::System.Diagnostics.TagList { { "mediator.request.name", "DeleteTour" }, { "mediator.outcome", outcome } });
            _instrumentation.RequestsDuration.Record(global::System.Diagnostics.Stopwatch.GetElapsedTime(sw).TotalMilliseconds, new global::System.Diagnostics.TagList { { "mediator.request.name", "DeleteTour" }, { "mediator.outcome", outcome } });
        }
    }

    /// <summary>
    /// Sends a <see cref="global::Demo.GetTourById"/> request through the generated mediator dispatch path.
    /// </summary>
    /// <param name="request">The request instance to dispatch.</param>
    /// <param name="ct">The cancellation token for the operation.</param>
    /// <returns>The produced response value.</returns>
    public async global::System.Threading.Tasks.ValueTask<string> Send(global::Demo.GetTourById request,
        global::System.Threading.CancellationToken ct)
    {
        var activity = _instrumentation.ActivitySource.StartActivity("mediator.send", global::System.Diagnostics.ActivityKind.Internal);
        activity?.SetTag("mediator.request.name", "GetTourById");
        activity?.SetTag("mediator.request.assembly", "SharedKernel.Mediator.Tests.Dynamic");
        activity?.SetTag("mediator.handler.name", "GetTourByIdHandler");
        activity?.SetTag("mediator.pipeline.depth", 0);
        var sw = global::System.Diagnostics.Stopwatch.GetTimestamp();
        var outcome = "success";
        try
        {
            var handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.GetTourByIdHandler>(Services);

            var result = await handler.Handle(request, ct).ConfigureAwait(false);
            activity?.SetTag("mediator.outcome", "success");
            activity?.SetStatus(global::System.Diagnostics.ActivityStatusCode.Ok);
            return result;
        }
        catch (global::System.OperationCanceledException)
        {
            outcome = "cancelled";
            activity?.SetTag("mediator.outcome", "cancelled");
            throw;
        }
        catch (global::System.Exception ex)
        {
            outcome = "error";
            activity?.SetTag("error.type", ex.GetType().Name);
            activity?.AddException(ex);
            activity?.SetStatus(global::System.Diagnostics.ActivityStatusCode.Error, ex.Message);
            activity?.SetTag("mediator.outcome", "error");
            throw;
        }
        finally
        {
            activity?.Dispose();
            _instrumentation.RequestsTotal.Add(1, new global::System.Diagnostics.TagList { { "mediator.request.name", "GetTourById" }, { "mediator.outcome", outcome } });
            _instrumentation.RequestsDuration.Record(global::System.Diagnostics.Stopwatch.GetElapsedTime(sw).TotalMilliseconds, new global::System.Diagnostics.TagList { { "mediator.request.name", "GetTourById" }, { "mediator.outcome", outcome } });
        }
    }

    /// <summary>
    /// Sends a <see cref="global::Demo.LookupTour"/> request through the generated mediator dispatch path.
    /// </summary>
    /// <param name="request">The request instance to dispatch.</param>
    /// <param name="ct">The cancellation token for the operation.</param>
    /// <returns>The produced response value.</returns>
    public async global::System.Threading.Tasks.ValueTask<string> Send(global::Demo.LookupTour request,
        global::System.Threading.CancellationToken ct)
    {
        global::System.ArgumentNullException.ThrowIfNull(request);

        var activity = _instrumentation.ActivitySource.StartActivity("mediator.send", global::System.Diagnostics.ActivityKind.Internal);
        activity?.SetTag("mediator.request.name", "LookupTour");
        activity?.SetTag("mediator.request.assembly", "SharedKernel.Mediator.Tests.Dynamic");
        activity?.SetTag("mediator.handler.name", "LookupTourHandler");
        activity?.SetTag("mediator.pipeline.depth", 0);
        var sw = global::System.Diagnostics.Stopwatch.GetTimestamp();
        var outcome = "success";
        try
        {
            var handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.LookupTourHandler>(Services);

            var result = await handler.Handle(request, ct).ConfigureAwait(false);
            activity?.SetTag("mediator.outcome", "success");
            activity?.SetStatus(global::System.Diagnostics.ActivityStatusCode.Ok);
            return result;
        }
        catch (global::System.OperationCanceledException)
        {
            outcome = "cancelled";
            activity?.SetTag("mediator.outcome", "cancelled");
            throw;
        }
        catch (global::System.Exception ex)
        {
            outcome = "error";
            activity?.SetTag("error.type", ex.GetType().Name);
            activity?.AddException(ex);
            activity?.SetStatus(global::System.Diagnostics.ActivityStatusCode.Error, ex.Message);
            activity?.SetTag("mediator.outcome", "error");
            throw;
        }
        finally
        {
            activity?.Dispose();
            _instrumentation.RequestsTotal.Add(1, new global::System.Diagnostics.TagList { { "mediator.request.name", "LookupTour" }, { "mediator.outcome", outcome } });
            _instrumentation.RequestsDuration.Record(global::System.Diagnostics.Stopwatch.GetElapsedTime(sw).TotalMilliseconds, new global::System.Diagnostics.TagList { { "mediator.request.name", "LookupTour" }, { "mediator.outcome", outcome } });
        }
    }

    /// <summary>
    /// Sends a <see cref="global::Demo.MissingTour"/> request through the generated mediator dispatch path.
    /// </summary>
    /// <param name="request">The request instance to dispatch.</param>
    /// <param name="ct">The cancellation token for the operation.</param>
    /// <returns>The produced response value.</returns>
    public global::System.Threading.Tasks.ValueTask<string> Send(global::Demo.MissingTour request,
        global::System.Threading.CancellationToken ct)
    {
        global::System.ArgumentNullException.ThrowIfNull(request);

        throw new global::System.NotSupportedException($"Generated request dispatch is not available for request type '{request.GetType().FullName}'.");
    }

    /// <summary>
    /// Sends a <see cref="global::Demo.StreamTours"/> stream through the generated mediator dispatch path.
    /// </summary>
    /// <param name="request">The stream request instance to dispatch.</param>
    /// <param name="ct">The cancellation token for the operation.</param>
    /// <returns>The produced response stream.</returns>
    public global::System.Collections.Generic.IAsyncEnumerable<string> Send(global::Demo.StreamTours request,
        global::System.Threading.CancellationToken ct)
    {
        global::System.ArgumentNullException.ThrowIfNull(request);

        return SendStream_0000(request, ct);
    }

    private async global::System.Collections.Generic.IAsyncEnumerable<string> SendStream_0000(global::Demo.StreamTours request,
        [global::System.Runtime.CompilerServices.EnumeratorCancellation] global::System.Threading.CancellationToken ct)
    {
        var activity = _instrumentation.ActivitySource.StartActivity("mediator.stream", global::System.Diagnostics.ActivityKind.Internal);
        activity?.SetTag("mediator.request.name", "StreamTours");
        activity?.SetTag("mediator.request.assembly", "SharedKernel.Mediator.Tests.Dynamic");
        activity?.SetTag("mediator.handler.name", "StreamToursHandler");
        var outcome = "success";
        var handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.StreamToursHandler>(Services);

        var enumerator = handler.Handle(request, ct).GetAsyncEnumerator(ct);
        try
        {
            while (true)
            {
                bool hasNext;
                try
                {
                    hasNext = await enumerator.MoveNextAsync();
                }
                catch (global::System.OperationCanceledException)
                {
                    outcome = "cancelled";
                    activity?.SetTag("mediator.outcome", "cancelled");
                    throw;
                }
                catch (global::System.Exception ex)
                {
                    outcome = "error";
                    activity?.SetTag("error.type", ex.GetType().Name);
                    activity?.AddException(ex);
                    activity?.SetStatus(global::System.Diagnostics.ActivityStatusCode.Error, ex.Message);
                    activity?.SetTag("mediator.outcome", "error");
                    throw;
                }
                if (!hasNext)
                {
                    activity?.SetTag("mediator.outcome", "success");
                    activity?.SetStatus(global::System.Diagnostics.ActivityStatusCode.Ok);
                    break;
                }
                yield return enumerator.Current;
            }
        }
        finally
        {
            await enumerator.DisposeAsync();
            activity?.Dispose();
            _instrumentation.StreamsTotal.Add(1, new global::System.Diagnostics.TagList { { "mediator.request.name", "StreamTours" }, { "mediator.outcome", outcome } });
        }
    }

    /// <inheritdoc />
    public global::System.Threading.Tasks.ValueTask<TResponse> Send<TResponse>(
        global::SharedKernel.Mediator.IRequest<TResponse> request,
        global::System.Threading.CancellationToken ct)
    {
        global::System.ArgumentNullException.ThrowIfNull(request);

        return GeneratedDispatch.Send<TResponse>(this, request, ct);
    }

    /// <summary>
    /// Sends a stream request instance through the generated stream-dispatch path.
    /// </summary>
    /// <param name="request">The stream request instance to dispatch.</param>
    /// <param name="ct">The cancellation token for the operation.</param>
    /// <returns>The produced response stream.</returns>
    public global::System.Collections.Generic.IAsyncEnumerable<TResponse> Send<TResponse>(
        global::SharedKernel.Mediator.IStreamRequest<TResponse> request,
        global::System.Threading.CancellationToken ct)
    {
        global::System.ArgumentNullException.ThrowIfNull(request);

        return GeneratedDispatch.Send<TResponse>(this, request, ct);
    }

    /// <summary>
    /// Sends a request instance through the generated object-dispatch path.
    /// </summary>
    /// <param name="request">The boxed request instance to dispatch.</param>
    /// <param name="ct">The cancellation token for the operation.</param>
    /// <returns>The boxed response value produced by the generated dispatch path.</returns>
    public global::System.Threading.Tasks.ValueTask<object?> SendObject(
        object request,
        global::System.Threading.CancellationToken ct)
    {
        global::System.ArgumentNullException.ThrowIfNull(request);

        return GeneratedDispatch.SendObject(this, request, ct);
    }

    /// <inheritdoc />
    public global::System.Threading.Tasks.ValueTask Publish<TNotification>(
        TNotification notification,
        global::System.Threading.CancellationToken ct)
        where TNotification : global::SharedKernel.Mediator.INotification
    {
        global::System.ArgumentNullException.ThrowIfNull(notification);

        return GeneratedDispatch.Publish(this, notification, ct);
    }
}
