namespace SharedKernel.Documentation.Tests;

internal static class DocumentationTestContent
{
    public static string GeneratedBlockDocument(string line) =>
        $$"""
        # Overview

        <!-- generated:sample:start -->
        <!-- Generated by old-generator. Do not edit by hand. -->

        ```mermaid
        flowchart LR
            {{line}}
        ```
        <!-- generated:sample:end -->
        """;

    public static string GeneratorConfig(string line, string targetPath = "overview.md") =>
        $$"""
        {
          "docsPath": "docs/architecture",
          "generatorName": "test-generator",
          "blocks": [
            {
              "name": "sample",
              "targetPath": "{{targetPath}}",
              "kind": "mermaid-flowchart",
              "flowchart": "flowchart LR",
              "lines": ["    {{line}}"]
            }
          ]
        }
        """;

    public static string MissingTargetPathConfig() =>
        """
        {
          "docsPath": "docs/architecture",
          "generatorName": "test-generator",
          "blocks": [
            {
              "name": "sample",
              "kind": "mermaid-flowchart",
              "lines": []
            }
          ]
        }
        """;

    public static string EscapingDocsPathConfig() =>
        """
        {
          "docsPath": "../outside",
          "generatorName": "test-generator",
          "blocks": [
            {
              "name": "sample",
              "targetPath": "overview.md",
              "kind": "mermaid-flowchart",
              "lines": []
            }
          ]
        }
        """;

    public static string TwoBlockConfig() =>
        """
        {
          "docsPath": "docs/architecture",
          "generatorName": "test-generator",
          "blocks": [
            {
              "name": "first",
              "targetPath": "first.md",
              "kind": "mermaid-flowchart",
              "lines": ["    first[First]"]
            },
            {
              "name": "second",
              "targetPath": "second.md",
              "kind": "mermaid-flowchart",
              "lines": ["    second[Second]"]
            }
          ]
        }
        """;

    public static string TwoBlocksSameTargetConfig() =>
        """
        {
          "docsPath": "docs/architecture",
          "generatorName": "test-generator",
          "blocks": [
            {
              "name": "first",
              "targetPath": "overview.md",
              "kind": "mermaid-flowchart",
              "lines": ["    first[First]"]
            },
            {
              "name": "second",
              "targetPath": "overview.md",
              "kind": "mermaid-flowchart",
              "lines": ["    second[Second]"]
            }
          ]
        }
        """;

    public static string GeneratedBlocksDocument(params string[] blockNames) =>
        string.Join(
            '\n',
            [
                "# Overview",
                string.Empty,
                .. blockNames.SelectMany(blockName => new[]
                {
                    $"<!-- generated:{blockName}:start -->",
                    "old",
                    $"<!-- generated:{blockName}:end -->",
                    string.Empty,
                }),
            ]);

    public static string RepositorySourcesConfig() =>
        """
        {
          "docsPath": "docs/architecture",
          "generatorName": "test-generator",
          "blocks": [
            {
              "name": "apphost",
              "targetPath": "overview.md",
              "kind": "apphost-resources",
              "sourcePath": "apphost/Program.cs",
              "labels": {
                "admin": "Admin database",
                "api": "API service"
              }
            },
            {
              "name": "projects",
              "targetPath": "overview.md",
              "kind": "project-references",
              "sourcePath": "src",
              "projectFilter": "src-excluding-sharedkernel"
            },
            {
              "name": "endpoints",
              "targetPath": "overview.md",
              "kind": "endpoint-routes",
              "sourcePath": "src",
              "routePrefixes": {
                "customersGroup": "/customers",
                "managementCatalog": "/api/v1/catalog",
                "publicCatalogGroup": "/api/v1/public/catalog"
              }
            },
            {
              "name": "events",
              "targetPath": "overview.md",
              "kind": "integration-events",
              "sourcePath": "src"
            },
            {
              "name": "jobs",
              "targetPath": "overview.md",
              "kind": "github-actions-jobs",
              "sourcePath": ".github/workflows/ci.yml",
              "triggerLabel": "Pull request"
            },
            {
              "name": "workflows",
              "targetPath": "overview.md",
              "kind": "github-actions-workflows",
              "sourcePath": ".github/workflows",
              "rootLabel": "Repository",
              "excludedWorkflowFileName": "excluded.yml"
            }
          ]
        }
        """;

    public static string UnknownProjectFilterConfig() =>
        """
        {
          "docsPath": "docs/architecture",
          "generatorName": "test-generator",
          "blocks": [
            {
              "name": "projects",
              "targetPath": "overview.md",
              "kind": "project-references",
              "sourcePath": "src",
              "projectFilter": "unknown"
            }
          ]
        }
        """;

    public static string SharedKernelProjectFilterConfig() =>
        """
        {
          "docsPath": "docs/architecture",
          "generatorName": "test-generator",
          "blocks": [
            {
              "name": "projects",
              "targetPath": "overview.md",
              "kind": "project-references",
              "sourcePath": ".",
              "projectFilter": "sharedkernel"
            }
          ]
        }
        """;

    public static string UnknownBlockKindConfig() =>
        """
        {
          "docsPath": "docs/architecture",
          "generatorName": "test-generator",
          "blocks": [
            {
              "name": "sample",
              "targetPath": "overview.md",
              "kind": "unknown"
            }
          ]
        }
        """;

    public static string MissingDocsPathConfig() =>
        """
        {
          "generatorName": "test-generator",
          "blocks": [
            {
              "name": "sample",
              "targetPath": "overview.md",
              "kind": "mermaid-flowchart",
              "lines": []
            }
          ]
        }
        """;

    public static string MissingGeneratorNameConfig() =>
        """
        {
          "docsPath": "docs/architecture",
          "blocks": [
            {
              "name": "sample",
              "targetPath": "overview.md",
              "kind": "mermaid-flowchart",
              "lines": []
            }
          ]
        }
        """;

    public static string MissingBlocksConfig() =>
        """
        {
          "docsPath": "docs/architecture",
          "generatorName": "test-generator"
        }
        """;

    public static string NullBlocksConfig() =>
        """
        {
          "docsPath": "docs/architecture",
          "generatorName": "test-generator",
          "blocks": null
        }
        """;

    public static string NullBlockEntryConfig() =>
        """
        {
          "docsPath": "docs/architecture",
          "generatorName": "test-generator",
          "blocks": [null]
        }
        """;

    public static string DuplicateBlockNamesConfig() =>
        """
        {
          "docsPath": "docs/architecture",
          "generatorName": "test-generator",
          "blocks": [
            {
              "name": "sample",
              "targetPath": "overview.md",
              "kind": "mermaid-flowchart",
              "lines": []
            },
            {
              "name": "sample",
              "targetPath": "overview.md",
              "kind": "mermaid-flowchart",
              "lines": []
            }
          ]
        }
        """;

    public static string SwitchFactConformanceConfig() =>
        """
        {
          "checks": [
            {
              "name": "sample-events",
              "documentPath": "docs/architecture/FLOWS.md",
              "markerName": "sample-events",
              "factName": "current-event",
              "switchSources": [
                {
                  "sourcePath": "src/SampleAggregate.cs",
                  "methodName": "Apply",
                  "parameterCount": 1
                },
                {
                  "sourcePath": "src/SampleProjection.cs",
                  "methodName": "Apply",
                  "parameterCount": 1
                }
              ]
            }
          ]
        }
        """;

    public static string RegistrationFactConformanceConfig(bool requireMissingInvocation = false) =>
        $$"""
        {
          "checks": [
            {
              "name": "sample-runtime",
              "documentPath": "docs/architecture/FLOWS.md",
              "markerName": "sample-runtime",
              "factName": "current-runtime",
              "registrationSources": [
                {
                  "sourcePath": "src/SampleRuntime.cs",
                  "methodName": "Configure",
                  "parameterCount": 1
                }
              ],
              "includedIdentifierFragments": ["IntegrationEvent"],
              "includedIdentifiers": ["CatalogProjectionHostedService"],
              "invocationRequirements": [
                {
                  "sourcePath": "src/SampleRuntime.cs",
                  "methodName": "Entry",
                  "parameterCount": 1,
                  "invokedMethodName": "{{(requireMissingInvocation ? "Missing" : "Configure")}}",
                  "expectedCount": 1,
                  "expectedArguments": ["addRuntime: null"]
                }
              ]
            }
          ]
        }
        """;

    public static string ExpectedFactConformanceConfig() =>
        """
        {
          "checks": [
            {
              "name": "documentation-index",
              "documentPath": "docs/README.md",
              "markerName": "documentation-index",
              "factName": "current-requirement",
              "contentBlockMarkers": ["documentation-index-table"],
              "expectedIdentifiers": [
                "deprecated-docs-reviewed",
                "guidance-centralized"
              ]
            }
          ]
        }
        """;

    public static string GovernanceFactConformanceConfig() =>
        """
        {
          "checks": [
            {
              "name": "documentation-governance",
              "documentPath": "docs/DOCUMENTATION_GOVERNANCE.md",
              "markerName": "documentation-governance",
              "factName": "current-standard",
              "contentBlockMarkers": [
                "required-sections-checklist",
                "provenance-expectations",
                "small-doc-exemption"
              ],
              "expectedIdentifiers": [
                "generated-manual-provenance-explicit",
                "required-sections-by-document-type",
                "small-focused-docs-exempt"
              ]
            }
          ]
        }
        """;

    public static string GovernanceDocumentWithoutContent(string removedBlock)
    {
        var requiredSections = removedBlock == "required-sections-checklist"
            ? string.Empty
            : "| Class | Required blocks |";
        var provenance = removedBlock == "provenance-expectations"
            ? string.Empty
            : "- Generated documents identify their owning generator.";
        var exemption = removedBlock == "small-doc-exemption"
            ? string.Empty
            : "Short focused documents remain exempt.";

        return $$"""
        <!-- doc-fact:documentation-governance:start -->
        - current-standard: `generated-manual-provenance-explicit`
        - current-standard: `required-sections-by-document-type`
        - current-standard: `small-focused-docs-exempt`
        <!-- doc-fact:documentation-governance:end -->

        <!-- doc-content:required-sections-checklist:start -->
        {{requiredSections}}
        <!-- doc-content:required-sections-checklist:end -->

        <!-- doc-content:provenance-expectations:start -->
        {{provenance}}
        <!-- doc-content:provenance-expectations:end -->

        <!-- doc-content:small-doc-exemption:start -->
        {{exemption}}
        <!-- doc-content:small-doc-exemption:end -->
        """;
    }

    public static string SampleAggregateSource() =>
        """
        internal sealed class SampleAggregate
        {
            private static int Apply(object value)
            {
                if (value is bool flag)
                {
                    return flag ? 1 : 0;
                }

                return value switch
                {
                    FirstEvent { } => 1,
                    SecondEvent { } => 2,
                    _ => 0
                };
            }
        }
        """;

    public static string SampleProjectionSource() =>
        """
        internal sealed class SampleProjection
        {
            private static int Apply(object value)
            {
                switch (value)
                {
                    case FirstEvent firstEvent:
                        _ = firstEvent;
                        return 1;
                    case SecondEvent { }:
                        return 2;
                    default:
                        return 0;
                }
            }
        }
        """;

    public static string SampleRuntimeSource() =>
        """
        internal static class SampleRuntime
        {
            public static object Entry(object builder) =>
                builder.Configure(addRuntime: null);

            private static void Configure(object services)
            {
                services.AddHostedService<DocumentAuditRetentionHostedService>();
                services.AddIntegrationEventOutbox();
                services.AddHostedService<CatalogProjectionHostedService>();
            }
        }
        """;

    public static string AppHostProgram() =>
        """
        var builder = DistributedApplication.CreateBuilder(args);
        var includeDeveloperTooling = profile.IncludesDeveloperTooling();
        var postgres = builder.AddPostgres("postgres");
        var admin = postgres.AddDatabase("admin");
        var clamAv = includeDeveloperTooling ? builder.AddClamAv("clam") : null;
        var api = builder.AddProject(api, admin, clamAv);
        builder.AddDockerfile(worker, api);
        """;

    public static string AppProject() =>
        """
        <Project Sdk="Microsoft.NET.Sdk">
            <ItemGroup>
                <ProjectReference Include="../Lib/Lib.csproj" />
            </ItemGroup>
        </Project>
        """;

    public static string EmptyProject() =>
        """
        <Project Sdk="Microsoft.NET.Sdk" />
        """;

    public static string CustomerEndpoints()
    {
        var padding = string.Join(
            '\n',
            Enumerable.Repeat("            // endpoint-chain scan padding", 129));

        return $$""""
        internal static class CustomerEndpoints
        {
            public static WebApplication MapCustomerEndpoints(this WebApplication app)
            {
                var customersGroup = app.MapCustomersGroup();
                customersGroup.MapGet("/", GetAllCustomers)
                    .WithName("GetCustomers");
                customersGroup.MapPost("/", CreateCustomer)
                    .RequireAuthorization();
                customersGroup.MapGet("/unterminated-adjacent", GetUnterminatedAdjacent)
                    .WithDescription("Missing terminator")
                customersGroup.MapGet("/after-unterminated-adjacent", GetAfterUnterminatedAdjacent)
                    .RequireAuthorization();
                customersGroup.MapGet("/raw-multiline", GetRawMultiline)
                    .WithDescription(
                        """
                        public endpoint;
                        """)
                    .RequireAuthorization();
                customersGroup.MapGet("/brace-literal", GetBraceLiteral)
                    .WithDescription("Literal {");
                customersGroup.MapGet("/verbatim-multiline", GetVerbatimMultiline)
                    .WithDescription(@"Literal \
                        {");
                customersGroup.MapGet("/later-secured", GetLaterSecured)
                    .RequireAuthorization();
                customersGroup.MapGet("/char-literal", GetCharLiteral)
                    .WithMetadata('{');
                customersGroup.MapGet("/after-char-secured", GetAfterCharSecured)
                    .RequireAuthorization();
                customersGroup.MapGet("/line-comment", GetLineComment)
                    .WithDescription("Line comment"); // {
                customersGroup.MapGet("/after-comment-secured", GetAfterCommentSecured)
                    .RequireAuthorization();
                customersGroup.MapGet("/block-comment", GetBlockComment)
                    /* {
                       ; */
                    .WithDescription("Block comment");
                customersGroup.MapGet("/after-block-comment-secured", GetAfterBlockCommentSecured)
                    .RequireAuthorization();
                customersGroup.MapGet("/unterminated", GetUnterminated)
                    .WithDescription("Missing terminator")
        {{padding}}
                customersGroup.MapGet("/after-padding-secured", GetAfterPaddingSecured)
                    .RequireAuthorization();
                var publicCatalogGroup = app.MapPublicCatalogGroup();
                publicCatalogGroup.MapGet("/content/{key}", GetPublicContent)
                    .WithName("GetPublicContent");
                var managementCatalog = app.MapCatalogGroup();
                managementCatalog.MapPut("/tours/{id}/presentation", UpdatePresentation)
                    .AddOpenApiOperationTransformer((operation, _, _) =>
                    {
                        operation.Description = "Updates presentation.";
                        operation.Summary = "Update";
                        operation.Deprecated = false;
                        operation.Tags = [];
                        operation.Parameters = [];
                        return Task.CompletedTask;
                    })
                    .RequireAuthorization();
                customersGroup.MapGet("/last-unsecured", GetLastUnsecured);
                customersGroup.MapGet(RouteNames.Hidden, GetHidden)
                    .RequireAuthorization();
                customersGroup.MapGet("/method-boundary", GetMethodBoundary);
                return app;
            }

            private static void
                ConfigureAuthorization<T>()
            {
                builder.RequireAuthorization();
            }
        }
        """";
    }

    public static string AdminTourCreatedIntegrationEvent() =>
        """
        public sealed record AdminTourCreatedIntegrationEvent(
            Guid EventId) : IIntegrationEvent
        {
            public static string EventType => "admin.tour.created";
            public static int EventVersion => 1;
        }
        """;

    public static string TourIntegrationEventMappings() =>
        """
        internal static class TourIntegrationEventMappings
        {
            public static AdminTourCreatedIntegrationEvent MapTourCreated(Guid id)
            {
                return new AdminTourCreatedIntegrationEvent(id);
            }
        }
        """;

    public static string AdminTourCreatedIntegrationHandler() =>
        """
        internal sealed class AdminTourCreatedIntegrationHandler : IIntegrationEventHandler<AdminTourCreatedIntegrationEvent>
        {
        }
        """;

    public static string ApplicationDependencyInjection() =>
        """
        public static class ApplicationDependencyInjection
        {
            public static void Add(IServiceCollection services)
            {
                services.AddIntegrationEventConsumer<AdminTourCreatedIntegrationEvent>(
                    AdminTourCreatedIntegrationEvent.EventType,
                    AdminIntegrationEventJsonContext.Default.AdminTourCreatedIntegrationEvent);
            }
        }
        """;

    public static string CiWorkflow() =>
        """
        name: CI
        on: [pull_request]
        jobs:
          build:
            name: Build job
          test:
            name: "${{ matrix.display_name }}"
            needs: build
          deploy:
            needs:
              - test
        """;

    public static string ReleaseWorkflow() =>
        """
        name: Release workflow
        on: [workflow_dispatch]
        jobs:
          release:
            name: Release job
        """;

    public static string ExcludedWorkflow() =>
        """
        name: Excluded workflow
        on: [push]
        jobs:
          skipped:
            name: Skipped job
        """;
}
