namespace SharedKernel.Documentation.Tests;

[Trait(Testing.SharedKernelTestTraitNames.CapabilityName, TestTraits.DocumentationGenerationCapability)]
public sealed class DocumentationGeneratorTests
{
    [Fact]
    public void Run_updates_configured_generated_block()
    {
        // Arrange
        using var workspace = new TemporaryDocumentationWorkspace();
        workspace.WriteArchitectureDoc("overview.md", DocumentationTestContent.GeneratedBlockDocument("old[Old]"));
        workspace.WriteConfig(DocumentationTestContent.GeneratorConfig("newNode[New node]"));

        // Act
        var result = DocumentationGenerator.Run(workspace.RootPath, "docs/architecture/generated-diagrams.json", checkOnly: false);
        var updated = workspace.ReadArchitectureDoc("overview.md");

        // Assert
        result.ChangedFiles.ShouldBe(["docs/architecture/overview.md"]);
        updated.ShouldContain("<!-- Generated by test-generator. Do not edit by hand. -->", StringComparison.Ordinal);
        updated.ShouldContain("flowchart LR", StringComparison.Ordinal);
        updated.ShouldContain("newNode[New node]", StringComparison.Ordinal);
        updated.ShouldNotContain("old[Old]");
    }

    [Fact]
    public void Run_check_detects_stale_generated_block_without_writing()
    {
        // Arrange
        using var workspace = new TemporaryDocumentationWorkspace();
        workspace.WriteArchitectureDoc("overview.md", DocumentationTestContent.GeneratedBlockDocument("old[Old]"));
        workspace.WriteConfig(DocumentationTestContent.GeneratorConfig("newNode[New node]"));

        // Act
        var result = DocumentationGenerator.Run(workspace.RootPath, "docs/architecture/generated-diagrams.json", checkOnly: true);
        var unchanged = workspace.ReadArchitectureDoc("overview.md");

        // Assert
        result.ChangedFiles.ShouldBe(["docs/architecture/overview.md"]);
        unchanged.ShouldContain("old[Old]", StringComparison.Ordinal);
        unchanged.ShouldNotContain("newNode[New node]");
    }

    [Fact]
    public void Run_preserves_dollar_replacement_tokens_in_generated_block()
    {
        // Arrange
        using var workspace = new TemporaryDocumentationWorkspace();
        workspace.WriteArchitectureDoc("overview.md", DocumentationTestContent.GeneratedBlockDocument("old[Old]"));
        workspace.WriteConfig(DocumentationTestContent.GeneratorConfig("literal[$&]"));

        // Act
        DocumentationGenerator.Run(workspace.RootPath, "docs/architecture/generated-diagrams.json", checkOnly: false);
        var updated = workspace.ReadArchitectureDoc("overview.md");

        // Assert
        updated.ShouldContain("literal[$&]", StringComparison.Ordinal);
        updated.ShouldNotContain("old[Old]");
    }
}
