namespace SharedKernel.Documentation.Tests;

internal static class DocumentationTestContent
{
    public static string GeneratedBlockDocument(string line) =>
        $$"""
        # Overview

        <!-- generated:sample:start -->
        <!-- Generated by old-generator. Do not edit by hand. -->

        ```mermaid
        flowchart LR
            {{line}}
        ```
        <!-- generated:sample:end -->
        """;

    public static string GeneratorConfig(string line) =>
        $$"""
        {
          "docsPath": "docs/architecture",
          "generatorName": "test-generator",
          "blocks": [
            {
              "name": "sample",
              "kind": "mermaid-flowchart",
              "flowchart": "flowchart LR",
              "lines": ["    {{line}}"]
            }
          ]
        }
        """;

    public static string GeneratedBlocksDocument(params string[] blockNames) =>
        string.Join(
            '\n',
            [
                "# Overview",
                string.Empty,
                .. blockNames.SelectMany(blockName => new[]
                {
                    $"<!-- generated:{blockName}:start -->",
                    "old",
                    $"<!-- generated:{blockName}:end -->",
                    string.Empty,
                }),
            ]);

    public static string RepositorySourcesConfig() =>
        """
        {
          "docsPath": "docs/architecture",
          "generatorName": "test-generator",
          "blocks": [
            {
              "name": "apphost",
              "kind": "apphost-resources",
              "sourcePath": "apphost/Program.cs",
              "labels": {
                "admin": "Admin database",
                "api": "API service"
              }
            },
            {
              "name": "projects",
              "kind": "project-references",
              "sourcePath": "src",
              "projectFilter": "src-excluding-sharedkernel"
            },
            {
              "name": "endpoints",
              "kind": "endpoint-routes",
              "sourcePath": "src",
              "routePrefixes": {
                "customersGroup": "/customers",
                "publicCatalogGroup": "/api/v1/public/catalog"
              }
            },
            {
              "name": "events",
              "kind": "integration-events",
              "sourcePath": "src"
            },
            {
              "name": "jobs",
              "kind": "github-actions-jobs",
              "sourcePath": ".github/workflows/ci.yml",
              "triggerLabel": "Pull request"
            },
            {
              "name": "workflows",
              "kind": "github-actions-workflows",
              "sourcePath": ".github/workflows",
              "rootLabel": "Repository",
              "excludedWorkflowFileName": "excluded.yml"
            }
          ]
        }
        """;

    public static string UnknownProjectFilterConfig() =>
        """
        {
          "docsPath": "docs/architecture",
          "generatorName": "test-generator",
          "blocks": [
            {
              "name": "projects",
              "kind": "project-references",
              "sourcePath": "src",
              "projectFilter": "unknown"
            }
          ]
        }
        """;

    public static string MissingDocsPathConfig() =>
        """
        {
          "generatorName": "test-generator",
          "blocks": [
            {
              "name": "sample",
              "kind": "mermaid-flowchart",
              "lines": []
            }
          ]
        }
        """;

    public static string MissingGeneratorNameConfig() =>
        """
        {
          "docsPath": "docs/architecture",
          "blocks": [
            {
              "name": "sample",
              "kind": "mermaid-flowchart",
              "lines": []
            }
          ]
        }
        """;

    public static string MissingBlocksConfig() =>
        """
        {
          "docsPath": "docs/architecture",
          "generatorName": "test-generator"
        }
        """;

    public static string NullBlocksConfig() =>
        """
        {
          "docsPath": "docs/architecture",
          "generatorName": "test-generator",
          "blocks": null
        }
        """;

    public static string DuplicateBlockNamesConfig() =>
        """
        {
          "docsPath": "docs/architecture",
          "generatorName": "test-generator",
          "blocks": [
            {
              "name": "sample",
              "kind": "mermaid-flowchart",
              "lines": []
            },
            {
              "name": "sample",
              "kind": "mermaid-flowchart",
              "lines": []
            }
          ]
        }
        """;

    public static string AppHostProgram() =>
        """
        var builder = DistributedApplication.CreateBuilder(args);
        var postgres = builder.AddPostgres("postgres");
        var admin = postgres.AddDatabase("admin");
        var api = builder.AddProject(api, admin);
        builder.AddDockerfile(worker, api);
        """;

    public static string AppProject() =>
        """
        <Project Sdk="Microsoft.NET.Sdk">
            <ItemGroup>
                <ProjectReference Include="../Lib/Lib.csproj" />
            </ItemGroup>
        </Project>
        """;

    public static string EmptyProject() =>
        """
        <Project Sdk="Microsoft.NET.Sdk" />
        """;

    public static string CustomerEndpoints() =>
        """
        internal static class CustomerEndpoints
        {
            public static WebApplication MapCustomerEndpoints(this WebApplication app)
            {
                var customersGroup = app.MapCustomersGroup();
                customersGroup.MapGet("/", GetAllCustomers)
                    .WithName("GetCustomers");
                customersGroup.MapPost("/", CreateCustomer)
                    .RequireAuthorization();
                var publicCatalogGroup = app.MapPublicCatalogGroup();
                publicCatalogGroup.MapGet("/content/{key}", GetPublicContent)
                    .WithName("GetPublicContent");
                return app;
            }
        }
        """;

    public static string AdminTourCreatedIntegrationEvent() =>
        """
        public sealed record AdminTourCreatedIntegrationEvent(
            Guid EventId) : IIntegrationEvent
        {
            public static string EventType => "admin.tour.created";
            public static int EventVersion => 1;
        }
        """;

    public static string TourIntegrationEventMappings() =>
        """
        internal static class TourIntegrationEventMappings
        {
            public static AdminTourCreatedIntegrationEvent MapTourCreated(Guid id)
            {
                return new AdminTourCreatedIntegrationEvent(id);
            }
        }
        """;

    public static string AdminTourCreatedIntegrationHandler() =>
        """
        internal sealed class AdminTourCreatedIntegrationHandler : IIntegrationEventHandler<AdminTourCreatedIntegrationEvent>
        {
        }
        """;

    public static string ApplicationDependencyInjection() =>
        """
        public static class ApplicationDependencyInjection
        {
            public static void Add(IServiceCollection services)
            {
                services.AddIntegrationEventConsumer(
                    AdminTourCreatedIntegrationEvent.EventType,
                    AdminIntegrationEventJsonContext.Default.AdminTourCreatedIntegrationEvent);
            }
        }
        """;

    public static string CiWorkflow() =>
        """
        name: CI
        on: [pull_request]
        jobs:
          build:
            name: Build job
          test:
            name: "Test job"
            needs: build
          deploy:
            needs:
              - test
        """;

    public static string ReleaseWorkflow() =>
        """
        name: Release workflow
        on: [workflow_dispatch]
        jobs:
          release:
            name: Release job
        """;

    public static string ExcludedWorkflow() =>
        """
        name: Excluded workflow
        on: [push]
        jobs:
          skipped:
            name: Skipped job
        """;
}
