// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ViajantesTurismo.Catalog.Infrastructure;

#nullable disable

namespace ViajantesTurismo.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260629144232_PersistPublicMediaImages")]
    partial class PersistPublicMediaImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ViajantesTurismo.Catalog.Domain.PublicContent.EditablePublicContent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PublicationState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("PublicContent", (string)null);
                });

            modelBuilder.Entity("ViajantesTurismo.Catalog.Infrastructure.CatalogTourReadModelEntity", b =>
                {
                    b.Property<Guid>("CatalogTourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdminTourId")
                        .HasColumnType("uuid");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<long>("Position")
                        .HasColumnType("bigint");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CatalogTourId");

                    b.HasIndex("AdminTourId")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("CatalogTourReadModels", (string)null);
                });

            modelBuilder.Entity("ViajantesTurismo.Catalog.Infrastructure.PublicMediaImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Attribution")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Caption")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Copyright")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceUri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PublicMediaImages", (string)null);
                });

            modelBuilder.Entity("ViajantesTurismo.Catalog.Infrastructure.PublicMediaImageResponsiveVariantEntity", b =>
                {
                    b.Property<Guid>("PublicMediaImageId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("PublicMediaImageId", "SortOrder");

                    b.ToTable("PublicMediaImageResponsiveVariants", (string)null);
                });

            modelBuilder.Entity("ViajantesTurismo.Catalog.Infrastructure.PublicMediaImageTourLinkEntity", b =>
                {
                    b.Property<Guid>("PublicMediaImageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CatalogTourId")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCover")
                        .HasColumnType("boolean");

                    b.HasKey("PublicMediaImageId", "CatalogTourId");

                    b.HasIndex("CatalogTourId", "DisplayOrder");

                    b.ToTable("PublicMediaImageTourLinks", (string)null);
                });

            modelBuilder.Entity("ViajantesTurismo.Catalog.Domain.PublicContent.EditablePublicContent", b =>
                {
                    b.OwnsMany("ViajantesTurismo.Catalog.Domain.PublicContent.PublicContentVariant", "Variants", b1 =>
                        {
                            b1.Property<Guid>("PublicContentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Language")
                                .HasColumnType("text");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)");

                            b1.Property<string>("MetaDescription")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<bool>("RequiresHumanReview")
                                .HasColumnType("boolean");

                            b1.Property<string>("SeoTitle")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("ShareSummary")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.HasKey("PublicContentId", "Language");

                            b1.ToTable("PublicContentVariants", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PublicContentId");
                        });

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("ViajantesTurismo.Catalog.Infrastructure.PublicMediaImageResponsiveVariantEntity", b =>
                {
                    b.HasOne("ViajantesTurismo.Catalog.Infrastructure.PublicMediaImageEntity", null)
                        .WithMany("ResponsiveVariants")
                        .HasForeignKey("PublicMediaImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ViajantesTurismo.Catalog.Infrastructure.PublicMediaImageTourLinkEntity", b =>
                {
                    b.HasOne("ViajantesTurismo.Catalog.Infrastructure.PublicMediaImageEntity", null)
                        .WithMany("TourLinks")
                        .HasForeignKey("PublicMediaImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ViajantesTurismo.Catalog.Infrastructure.PublicMediaImageEntity", b =>
                {
                    b.Navigation("ResponsiveVariants");

                    b.Navigation("TourLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
