// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ViajantesTurismo.Catalog.Infrastructure;

#nullable disable

namespace ViajantesTurismo.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ViajantesTurismo.Catalog.Domain.PublicContent.EditablePublicContent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PublicationState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("PublicContent", (string)null);
                });

            modelBuilder.Entity("ViajantesTurismo.Catalog.Domain.PublicContent.EditablePublicContent", b =>
                {
                    b.OwnsOne("ViajantesTurismo.Catalog.Domain.PublicContent.PublicContentVariant", "EnUs", b1 =>
                        {
                            b1.Property<Guid>("EditablePublicContentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)")
                                .HasColumnName("EnUsBody");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("EnUsLanguage");

                            b1.Property<string>("MetaDescription")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("EnUsMetaDescription");

                            b1.Property<bool>("RequiresHumanReview")
                                .HasColumnType("boolean")
                                .HasColumnName("EnUsRequiresHumanReview");

                            b1.Property<string>("SeoTitle")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("EnUsSeoTitle");

                            b1.Property<string>("ShareSummary")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("EnUsShareSummary");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("EnUsTitle");

                            b1.HasKey("EditablePublicContentId");

                            b1.ToTable("PublicContent");

                            b1.WithOwner()
                                .HasForeignKey("EditablePublicContentId");
                        });

                    b.OwnsOne("ViajantesTurismo.Catalog.Domain.PublicContent.PublicContentVariant", "PtBr", b1 =>
                        {
                            b1.Property<Guid>("EditablePublicContentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)")
                                .HasColumnName("PtBrBody");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PtBrLanguage");

                            b1.Property<string>("MetaDescription")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("PtBrMetaDescription");

                            b1.Property<bool>("RequiresHumanReview")
                                .HasColumnType("boolean")
                                .HasColumnName("PtBrRequiresHumanReview");

                            b1.Property<string>("SeoTitle")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("PtBrSeoTitle");

                            b1.Property<string>("ShareSummary")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("PtBrShareSummary");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("PtBrTitle");

                            b1.HasKey("EditablePublicContentId");

                            b1.ToTable("PublicContent");

                            b1.WithOwner()
                                .HasForeignKey("EditablePublicContentId");
                        });

                    b.Navigation("EnUs")
                        .IsRequired();

                    b.Navigation("PtBr")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
