<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>ViajantesTurismo.Admin.UnitTests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="SharedKernel.Testing.Assertions" />
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="xunit.v3.mtp-v2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\ViajantesTurismo.Admin.ApiService\ViajantesTurismo.Admin.ApiService.csproj"/>
        <ProjectReference Include="..\..\src\ViajantesTurismo.Admin.Application\ViajantesTurismo.Admin.Application.csproj"/>
        <ProjectReference Include="..\..\src\ViajantesTurismo.Admin.Infrastructure\ViajantesTurismo.Admin.Infrastructure.csproj"/>
        <ProjectReference Include="..\..\src\ViajantesTurismo.Admin.Contracts.Http\ViajantesTurismo.Admin.Contracts.Http.csproj"/>
        <ProjectReference Include="..\..\src\ViajantesTurismo.Admin.Contracts.IntegrationEvents\ViajantesTurismo.Admin.Contracts.IntegrationEvents.csproj"/>
        <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.Branding\SharedKernel.Branding.csproj" />
        <ProjectReference Include="..\..\src\ViajantesTurismo.Branding.Infrastructure\ViajantesTurismo.Branding.Infrastructure.csproj" />
        <ProjectReference Include="..\..\src\ViajantesTurismo.Catalog.Infrastructure\ViajantesTurismo.Catalog.Infrastructure.csproj" />
        <ProjectReference Include="..\..\src\ViajantesTurismo.MigrationService\ViajantesTurismo.MigrationService.csproj"/>
        <ProjectReference Include="..\..\src\ViajantesTurismo.Management.Security\ViajantesTurismo.Management.Security.csproj" />
        <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.EntityFrameworkCore\SharedKernel.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.DomainEvents.EntityFrameworkCore\SharedKernel.DomainEvents.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.Messaging.IntegrationEvents\SharedKernel.Messaging.IntegrationEvents.csproj" />
        <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.Messaging.IntegrationEvents.CloudEvents\SharedKernel.Messaging.IntegrationEvents.CloudEvents.csproj" />
        <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.Messaging.IntegrationEvents.EntityFrameworkCore\SharedKernel.Messaging.IntegrationEvents.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.MalwareScanning\SharedKernel.MalwareScanning.csproj" />
        <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.Testing\SharedKernel.Testing.csproj" />
        <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.Testing.Assertions\SharedKernel.Testing.Assertions.csproj" />
        <ProjectReference Include="..\ViajantesTurismo.Admin.Testing\ViajantesTurismo.Admin.Testing.csproj"/>
    </ItemGroup>

</Project>
