<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <!-- Blazor Server is not Native AOT-compatible. -->
        <IsAotCompatible>false</IsAotCompatible>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="ViajantesTurismo.Management.WebTests"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SharedKernel\SharedKernel.AspNetCore\SharedKernel.AspNetCore.csproj" />
        <ProjectReference Include="..\SharedKernel\SharedKernel.HttpClients\SharedKernel.HttpClients.csproj" />
        <ProjectReference Include="..\ViajantesTurismo.Admin.Contracts\ViajantesTurismo.Admin.Contracts.csproj"/>
        <ProjectReference Include="..\ViajantesTurismo.Catalog.Contracts\ViajantesTurismo.Catalog.Contracts.csproj"/>
        <ProjectReference Include="..\ViajantesTurismo.Resources\ViajantesTurismo.Resources.csproj"/>
        <ProjectReference Include="..\ViajantesTurismo.ServiceDefaults\ViajantesTurismo.ServiceDefaults.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.StackExchange.Redis.OutputCaching"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid"/>
    </ItemGroup>

</Project>
