<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <None Include="OpenApi/**/*.openapi.json" Pack="true" PackagePath="OpenApi/" />
        <None Include="OpenApi/README.md" Pack="true" PackagePath="OpenApi/" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <ProjectReference Include="..\SharedKernel\SharedKernel.IntegrationEvents\SharedKernel.IntegrationEvents.csproj" />
        <ProjectReference Include="..\SharedKernel\SharedKernel.Mediator.Abstractions\SharedKernel.Mediator.Abstractions.csproj" />
        <ProjectReference Include="..\SharedKernel\SharedKernel.HttpClients\SharedKernel.HttpClients.csproj" />
    </ItemGroup>

</Project>
