<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>ViajantesTurismo.Branding.ApiServiceTests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="System.Net" />
        <Using Include="System.Net.Http.Json" />
        <Using Include="Microsoft.AspNetCore.Http" />
        <Using Include="Microsoft.AspNetCore.Hosting" />
        <Using Include="Microsoft.AspNetCore.Mvc.Testing" />
        <Using Include="Microsoft.Extensions.DependencyInjection" />
        <Using Include="Microsoft.Extensions.DependencyInjection.Extensions" />
        <Using Include="SharedKernel.Branding" />
        <Using Include="SharedKernel.Testing.Assertions" />
        <Using Include="ViajantesTurismo.Branding.ApiServiceTests.Infrastructure" />
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="xunit.v3.mtp-v2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.Branding\SharedKernel.Branding.csproj" />
        <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.Messaging\SharedKernel.Messaging.csproj" />
        <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.Messaging.IntegrationEvents\SharedKernel.Messaging.IntegrationEvents.csproj" />
        <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.Messaging.IntegrationEvents.EntityFrameworkCore\SharedKernel.Messaging.IntegrationEvents.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.Testing.Assertions\SharedKernel.Testing.Assertions.csproj" />
        <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.Testing.AspNetCore\SharedKernel.Testing.AspNetCore.csproj" />
        <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.Testing\SharedKernel.Testing.csproj" />
        <ProjectReference Include="..\..\src\ViajantesTurismo.Branding.ApiService\ViajantesTurismo.Branding.ApiService.csproj" />
    </ItemGroup>

</Project>
