<Project Sdk="Microsoft.NET.Sdk.Worker">

    <ItemGroup>
        <ProjectReference Include="..\ViajantesTurismo.Catalog.Infrastructure\ViajantesTurismo.Catalog.Infrastructure.csproj" />
        <ProjectReference Include="..\ViajantesTurismo.ServiceDefaults\ViajantesTurismo.ServiceDefaults.csproj" />
    </ItemGroup>

</Project>
