using Microsoft.CodeAnalysis;

namespace SharedKernel.Domain.GeneratorTests;

[Trait(Testing.SharedKernelTestTraitNames.CapabilityName, TestTraits.IdentityCapability)]
public sealed class ModelIdentityGeneratorTests
{
    [Fact]
    public void Generates_identity_equality_for_opted_in_identified_partial_class()
    {
        // Arrange
        const string source = """
            namespace Demo;

            [GenerateModelSupport(Identity = true)]
            public sealed partial class Customer : IIdentified<int>
            {
                public int Id { get; private init; }
            }
            """;
        var compilation = GeneratorTestHarness.CreateCompilation(source);

        // Act
        var runResult = GeneratorTestHarness.RunGeneratorDriver(compilation);
        var generatedSource = GeneratorTestHarness.GetGeneratedSource(runResult, "Demo.Customer.ModelSupport.g.cs");

        // Assert
        Assert.Contains("// <auto-generated />", generatedSource, StringComparison.Ordinal);
        Assert.Contains("namespace Demo;", generatedSource, StringComparison.Ordinal);
        Assert.Contains("public partial class Customer", generatedSource, StringComparison.Ordinal);
        Assert.Contains("public override bool Equals(object? obj)", generatedSource, StringComparison.Ordinal);
        Assert.Contains("obj is not Customer other", generatedSource, StringComparison.Ordinal);
        Assert.Contains("GetType() != other.GetType()", generatedSource, StringComparison.Ordinal);
        Assert.Contains(".Default.Equals(Id, default!)", generatedSource, StringComparison.Ordinal);
        Assert.Contains("public override int GetHashCode()", generatedSource, StringComparison.Ordinal);
    }

    [Fact]
    public void Generates_default_safe_hash_code_for_reference_type_identity()
    {
        // Arrange
        const string source = """
            #nullable enable

            namespace Demo;

            [GenerateModelSupport(Identity = true)]
            public sealed partial class Customer : IIdentified<string>
            {
                public string Id { get; private init; } = null!;
            }
            """;
        var compilation = GeneratorTestHarness.CreateCompilation(source);

        // Act
        var outputCompilation = GeneratorTestHarness.RunGeneratorAndUpdateCompilation(compilation, out var runResult);
        var generatedSource = GeneratorTestHarness.GetGeneratedSource(runResult, "Demo.Customer.ModelSupport.g.cs");
        var errors = outputCompilation.GetDiagnostics(TestContext.Current.CancellationToken)
            .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .ToArray();

        // Assert
        runResult.Diagnostics.ShouldBeEmpty();
        errors.ShouldBeEmpty();
        generatedSource.ShouldContain(">.Default.Equals(Id, default!)", StringComparison.Ordinal);
        generatedSource.ShouldContain("return base.GetHashCode();", StringComparison.Ordinal);
        generatedSource.ShouldNotContain("ArgumentNullException.ThrowIfNull");
    }

    [Fact]
    public void Does_not_generate_when_identity_option_is_not_enabled()
    {
        // Arrange
        const string source = """
            namespace Demo;

            [GenerateModelSupport]
            public sealed partial class Customer : IIdentified<int>
            {
                public int Id { get; private init; }
            }
            """;
        var compilation = GeneratorTestHarness.CreateCompilation(source);

        // Act
        var runResult = GeneratorTestHarness.RunGeneratorDriver(compilation);

        // Assert
        Assert.Empty(runResult.Results.Single().GeneratedSources);
    }

    [Fact]
    public void Generates_identity_when_assembly_default_is_enabled_for_identified_models()
    {
        // Arrange
        const string source = """
            [assembly: GenerateModelSupportDefaults(Identity = true)]

            namespace Demo;

            public sealed partial class Customer : IIdentified<int>
            {
                public int Id { get; private init; }
            }
            """;
        var compilation = GeneratorTestHarness.CreateCompilation(source);

        // Act
        var runResult = GeneratorTestHarness.RunGeneratorDriver(compilation);
        var generatedSource = GeneratorTestHarness.GetGeneratedSource(runResult, "Demo.Customer.ModelSupport.g.cs");

        // Assert
        runResult.Diagnostics.ShouldBeEmpty();
        generatedSource.ShouldContain("public partial class Customer", StringComparison.Ordinal);
    }

    [Fact]
    public void Does_not_generate_identity_when_type_disables_assembly_default()
    {
        // Arrange
        const string source = """
            [assembly: GenerateModelSupportDefaults(Identity = true)]

            namespace Demo;

            [GenerateModelSupport(Identity = false)]
            public sealed partial class Customer : IIdentified<int>
            {
                public int Id { get; private init; }
            }
            """;
        var compilation = GeneratorTestHarness.CreateCompilation(source);

        // Act
        var runResult = GeneratorTestHarness.RunGeneratorDriver(compilation);

        // Assert
        runResult.Diagnostics.ShouldBeEmpty();
        runResult.Results.Single().GeneratedSources.ShouldBeEmpty();
    }

    [Fact]
    public void Reports_diagnostic_when_type_is_not_partial()
    {
        // Arrange
        const string source = """
            namespace Demo;

            [GenerateModelSupport(Identity = true)]
            public sealed class Customer : IIdentified<int>
            {
                public int Id { get; private init; }
            }
            """;
        var compilation = GeneratorTestHarness.CreateCompilation(source);

        // Act
        var runResult = GeneratorTestHarness.RunGeneratorDriver(compilation);
        var diagnostic = Assert.Single(runResult.Diagnostics);

        // Assert
        Assert.Equal("SKMDL001", diagnostic.Id);
        Assert.Equal(DiagnosticSeverity.Error, diagnostic.Severity);
    }

    [Fact]
    public void Reports_diagnostic_when_identified_interface_is_missing()
    {
        // Arrange
        const string source = """
            namespace Demo;

            [GenerateModelSupport(Identity = true)]
            public sealed partial class Customer
            {
                public int Id { get; private init; }
            }
            """;
        var compilation = GeneratorTestHarness.CreateCompilation(source);

        // Act
        var runResult = GeneratorTestHarness.RunGeneratorDriver(compilation);
        var diagnostic = Assert.Single(runResult.Diagnostics);

        // Assert
        Assert.Equal("SKMDL002", diagnostic.Id);
    }

    [Fact]
    public void Reports_diagnostic_when_attribute_suffix_requests_identity_without_identified_interface()
    {
        // Arrange
        const string source = """
            namespace Demo;

            [GenerateModelSupportAttribute(Identity = true)]
            public sealed partial class Customer
            {
                public int Id { get; private init; }
            }
            """;
        var compilation = GeneratorTestHarness.CreateCompilation(source);

        // Act
        var runResult = GeneratorTestHarness.RunGeneratorDriver(compilation);
        var diagnostic = runResult.Diagnostics.ShouldHaveSingleItem();

        // Assert
        diagnostic.Id.ShouldBe("SKMDL002");
    }

    [Fact]
    public void Reports_diagnostic_when_aliased_attribute_requests_identity_without_identified_interface()
    {
        // Arrange
        const string source = """
            using ModelSupport = SharedKernel.Domain.GenerateModelSupportAttribute;

            namespace Demo;

            [ModelSupport(Identity = true)]
            public sealed partial class Customer
            {
                public int Id { get; private init; }
            }
            """;
        var compilation = GeneratorTestHarness.CreateCompilation(source);

        // Act
        var runResult = GeneratorTestHarness.RunGeneratorDriver(compilation);
        var diagnostic = runResult.Diagnostics.ShouldHaveSingleItem();

        // Assert
        diagnostic.Id.ShouldBe("SKMDL002");
    }

    [Fact]
    public void Generates_identity_for_assembly_default_with_aliased_identified_interface()
    {
        // Arrange
        const string source = """
            using CustomerIdentity = SharedKernel.Domain.IIdentified<int>;

            [assembly: GenerateModelSupportDefaults(Identity = true)]

            namespace Demo;

            public sealed partial class Customer : CustomerIdentity
            {
                public int Id { get; private init; }
            }
            """;
        var compilation = GeneratorTestHarness.CreateCompilation(source);

        // Act
        var runResult = GeneratorTestHarness.RunGeneratorDriver(compilation);
        var generatedSource = GeneratorTestHarness.GetGeneratedSource(runResult, "Demo.Customer.ModelSupport.g.cs");

        // Assert
        runResult.Diagnostics.ShouldBeEmpty();
        generatedSource.ShouldContain("public partial class Customer", StringComparison.Ordinal);
    }

    [Fact]
    public void Reports_diagnostic_when_id_property_is_missing()
    {
        // Arrange
        const string source = """
            namespace Demo;

            [GenerateModelSupport(Identity = true)]
            public sealed partial class Customer : IIdentified<int>
            {
                int IIdentified<int>.Id => 42;
            }
            """;
        var compilation = GeneratorTestHarness.CreateCompilation(source);

        // Act
        var runResult = GeneratorTestHarness.RunGeneratorDriver(compilation);
        var diagnostic = Assert.Single(runResult.Diagnostics);

        // Assert
        Assert.Equal("SKMDL003", diagnostic.Id);
    }

    [Fact]
    public void Reports_diagnostic_when_id_type_does_not_match_identified_interface()
    {
        // Arrange
        const string source = """
            namespace Demo;

            [GenerateModelSupport(Identity = true)]
            public sealed partial class Customer : IIdentified<int>
            {
                public string Id { get; private init; } = "42";

                int IIdentified<int>.Id => 42;
            }
            """;
        var compilation = GeneratorTestHarness.CreateCompilation(source);

        // Act
        var runResult = GeneratorTestHarness.RunGeneratorDriver(compilation);
        var diagnostic = Assert.Single(runResult.Diagnostics);

        // Assert
        Assert.Equal("SKMDL004", diagnostic.Id);
    }

    [Fact]
    public void Reports_diagnostic_when_model_inherits_from_a_base_class()
    {
        // Arrange
        const string source = """
            namespace Demo;

            public abstract class CustomerBase
            {
            }

            [GenerateModelSupport(Identity = true)]
            public sealed partial class Customer : CustomerBase, IIdentified<int>
            {
                public int Id { get; private init; }
            }
            """;
        var compilation = GeneratorTestHarness.CreateCompilation(source);

        // Act
        var runResult = GeneratorTestHarness.RunGeneratorDriver(compilation);
        var diagnostic = Assert.Single(runResult.Diagnostics);

        // Assert
        Assert.Equal("SKMDL005", diagnostic.Id);
    }

    [Fact]
    public void Generates_distinct_sources_for_same_type_name_in_different_namespaces()
    {
        // Arrange
        const string source = """
            namespace First
            {
                [GenerateModelSupport(Identity = true)]
                public sealed partial class Customer : IIdentified<int>
                {
                    public int Id { get; private init; }
                }
            }

            namespace Second
            {
                [GenerateModelSupport(Identity = true)]
                public sealed partial class Customer : IIdentified<int>
                {
                    public int Id { get; private init; }
                }
            }
            """;
        var compilation = GeneratorTestHarness.CreateCompilation(source);

        // Act
        var runResult = GeneratorTestHarness.RunGeneratorDriver(compilation);
        var generatedSources = runResult.Results.Single().GeneratedSources;

        // Assert
        Assert.Empty(runResult.Diagnostics);
        Assert.Contains(generatedSources, source => string.Equals(source.HintName, "First.Customer.ModelSupport.g.cs", StringComparison.Ordinal));
        Assert.Contains(generatedSources, source => string.Equals(source.HintName, "Second.Customer.ModelSupport.g.cs", StringComparison.Ordinal));
    }

    [Fact]
    public void Generates_distinct_sources_for_underscored_model_names()
    {
        // Arrange
        const string source = """
            namespace Demo
            {
                [GenerateModelSupport(Identity = true)]
                public sealed partial class Tour_Code : IIdentified<int>
                {
                    public int Id { get; private init; }
                }
            }

            namespace Demo.Tour
            {
                [GenerateModelSupport(Identity = true)]
                public sealed partial class Code : IIdentified<int>
                {
                    public int Id { get; private init; }
                }
            }
            """;
        var compilation = GeneratorTestHarness.CreateCompilation(source);

        // Act
        var runResult = GeneratorTestHarness.RunGeneratorDriver(compilation);
        var generatedSources = runResult.Results.Single().GeneratedSources;

        // Assert
        runResult.Diagnostics.ShouldBeEmpty();
        generatedSources.ShouldContain(source => string.Equals(source.HintName, "Demo.Tour_Code.ModelSupport.g.cs", StringComparison.Ordinal));
        generatedSources.ShouldContain(source => string.Equals(source.HintName, "Demo.Tour.Code.ModelSupport.g.cs", StringComparison.Ordinal));
    }

    [Fact]
    public void Generates_once_when_same_partial_type_has_duplicate_identity_attributes()
    {
        // Arrange
        const string source = """
            namespace Demo;

            [GenerateModelSupport(Identity = true)]
            public sealed partial class Customer : IIdentified<int>
            {
                public int Id { get; private init; }
            }

            [GenerateModelSupport(Identity = true)]
            public sealed partial class Customer
            {
            }
            """;
        var compilation = GeneratorTestHarness.CreateCompilation(source);

        // Act
        var runResult = GeneratorTestHarness.RunGeneratorDriver(compilation);
        var generatedSources = runResult.Results.Single().GeneratedSources;

        // Assert
        Assert.Empty(runResult.Diagnostics);
        Assert.Single(generatedSources);
    }

    [Fact]
    public void Reports_diagnostic_when_model_is_nested()
    {
        // Arrange
        const string source = """
            namespace Demo;

            public sealed partial class Container
            {
                [GenerateModelSupport(Identity = true)]
                public sealed partial class Customer : IIdentified<int>
                {
                    public int Id { get; private init; }
                }
            }
            """;
        var compilation = GeneratorTestHarness.CreateCompilation(source);

        // Act
        var runResult = GeneratorTestHarness.RunGeneratorDriver(compilation);
        var diagnostic = Assert.Single(runResult.Diagnostics);

        // Assert
        Assert.Equal("SKMDL006", diagnostic.Id);
    }

    [Theory]
    [InlineData("public int Id { get; set; }")]
    [InlineData("public int Id { get; init; }")]
    [InlineData("public static int Id => 42;")]
    public void Reports_diagnostic_when_id_shape_is_not_stable(string idProperty)
    {
        // Arrange
        var source = $$"""
            namespace Demo;

            [GenerateModelSupport(Identity = true)]
            public sealed partial class Customer : IIdentified<int>
            {
                {{idProperty}}
            }
            """;
        var compilation = GeneratorTestHarness.CreateCompilation(source);

        // Act
        var runResult = GeneratorTestHarness.RunGeneratorDriver(compilation);
        var diagnostic = Assert.Single(runResult.Diagnostics);

        // Assert
        Assert.Equal("SKMDL007", diagnostic.Id);
    }

    [Fact]
    public void Allows_get_only_id_properties()
    {
        // Arrange
        const string source = """
            namespace Demo;

            [GenerateModelSupport(Identity = true)]
            public sealed partial class Customer : IIdentified<int>
            {
                public int Id => 42;
            }
            """;
        var compilation = GeneratorTestHarness.CreateCompilation(source);

        // Act
        var runResult = GeneratorTestHarness.RunGeneratorDriver(compilation);

        // Assert
        Assert.Empty(runResult.Diagnostics);
        Assert.Single(runResult.Results.Single().GeneratedSources);
    }

    [Fact]
    public void Reports_diagnostic_when_model_is_record_class()
    {
        // Arrange
        const string source = """
            namespace Demo;

            [GenerateModelSupport(Identity = true)]
            public sealed partial record Customer(int Id) : IIdentified<int>;
            """;
        var compilation = GeneratorTestHarness.CreateCompilation(source);

        // Act
        var runResult = GeneratorTestHarness.RunGeneratorDriver(compilation);
        var diagnostic = Assert.Single(runResult.Diagnostics);

        // Assert
        Assert.Equal("SKMDL008", diagnostic.Id);
    }

    [Fact]
    public void Reports_diagnostic_when_model_is_generic()
    {
        // Arrange
        const string source = """
            namespace Demo;

            [GenerateModelSupport(Identity = true)]
            public sealed partial class Customer<TId> : IIdentified<TId>
            {
                public TId Id { get; private init; } = default!;
            }
            """;
        var compilation = GeneratorTestHarness.CreateCompilation(source);

        // Act
        var runResult = GeneratorTestHarness.RunGeneratorDriver(compilation);
        var diagnostic = Assert.Single(runResult.Diagnostics);

        // Assert
        Assert.Equal("SKMDL009", diagnostic.Id);
    }
}
