#!/usr/bin/env python3

from __future__ import annotations

import argparse
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path


ROOT = Path.cwd()


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Update generated architecture diagrams."
    )
    parser.add_argument(
        "--check", action="store_true", help="Fail when generated diagrams are stale."
    )
    args = parser.parse_args()

    replacements = {
        "project-dependencies": project_dependencies_diagram(),
        "sharedkernel-dependencies": sharedkernel_dependencies_diagram(),
        "apphost-resources": apphost_resources_diagram(),
        "ci-main-jobs": ci_main_jobs_diagram(),
        "ci-supplemental-workflows": ci_supplemental_workflows_diagram(),
    }

    changed = []
    for path in sorted((ROOT / "docs/architecture").glob("*.md")):
        original = path.read_text(encoding="utf-8")
        updated = original
        for name, replacement in replacements.items():
            updated = replace_generated_block(updated, name, replacement)
        if updated != original:
            changed.append(path.relative_to(ROOT).as_posix())
            if not args.check:
                path.write_text(updated, encoding="utf-8")

    if args.check and changed:
        print("Generated architecture diagrams are stale:", file=sys.stderr)
        for path in changed:
            print(f"- {path}", file=sys.stderr)
        print("Run: python3 scripts/update-architecture-diagrams.py", file=sys.stderr)
        return 1

    if changed:
        print("Updated generated architecture diagrams:")
        for path in changed:
            print(f"- {path}")
    else:
        print("Generated architecture diagrams are current.")
    return 0


def replace_generated_block(text: str, name: str, replacement: str) -> str:
    pattern = re.compile(
        rf"<!-- generated:{re.escape(name)}:start -->.*?<!-- generated:{re.escape(name)}:end -->",
        re.DOTALL,
    )
    block = (
        f"<!-- generated:{name}:start -->\n"
        "<!-- Generated by scripts/update-architecture-diagrams.py. Do not edit by hand. -->\n\n"
        f"{replacement.rstrip()}\n"
        f"<!-- generated:{name}:end -->"
    )
    return pattern.sub(lambda _: block, text)


def project_dependencies_diagram() -> str:
    edges = project_reference_edges(
        lambda path: path.parts[0] == "src" and "SharedKernel" not in path.parts
    )
    lines = ["```mermaid", "flowchart TB"]
    lines.extend(format_edges(edges))
    lines.append("```")
    return "\n".join(lines)


def sharedkernel_dependencies_diagram() -> str:
    edges = project_reference_edges(
        lambda path: path.parts[:2] == ("src", "SharedKernel")
    )
    lines = ["```mermaid", "flowchart TB"]
    lines.extend(format_edges(edges))
    lines.append("```")
    return "\n".join(lines)


def project_reference_edges(include_project) -> list[tuple[str, str]]:
    edges: list[tuple[str, str]] = []
    for project in sorted(ROOT.glob("**/*.csproj")):
        relative = project.relative_to(ROOT)
        if not include_project(relative):
            continue
        source = project.stem
        root = ET.parse(project).getroot()
        for reference in root.findall(".//ProjectReference"):
            include = reference.attrib.get("Include")
            if not include:
                continue
            target = (project.parent / include).resolve().stem
            edges.append((source, target))
    return sorted(set(edges))


def apphost_resources_diagram() -> str:
    path = ROOT / "src/ViajantesTurismo.AppHost/AppHost.cs"
    variables: dict[str, str] = {}
    edges: list[tuple[str, str]] = []
    assignment = re.compile(r"var\s+(\w+)\s+=\s+([\w.]+)\.([A-Za-z0-9_]+)\(([^)]*)\);")

    for line in path.read_text(encoding="utf-8").splitlines():
        match = assignment.search(line)
        if not match:
            continue
        variable, receiver, method, args = match.groups()
        if method == "CreateBuilder":
            continue
        variables[variable] = apphost_label(variable, method)
        receiver_name = receiver.rsplit(".", 1)[-1]
        if receiver_name in variables:
            edges.append((variable, receiver_name))
        for arg in parse_apphost_args(args):
            if arg in variables:
                edges.append((variable, arg))

    invocation = re.compile(r"builder\.(Add[A-Za-z0-9_]+)\(([^)]*)\);")
    for line in path.read_text(encoding="utf-8").splitlines():
        match = invocation.search(line)
        if not match or "var " in line:
            continue
        method, args = match.groups()
        node = method[3:]
        variables[node] = apphost_label(node, method)
        for arg in parse_apphost_args(args):
            if arg in variables:
                edges.append((node, arg))

    lines = ["```mermaid", "flowchart LR"]
    for key, label in sorted(variables.items(), key=lambda item: item[1]):
        lines.append(f"    {node_id(key)}[{label}]")
    for source, target in sorted(set(edges)):
        lines.append(f"    {node_id(source)} --> {node_id(target)}")
    lines.append("```")
    return "\n".join(lines)


def parse_apphost_args(args: str) -> list[str]:
    return [arg.strip() for arg in args.split(",") if re.fullmatch(r"\w+", arg.strip())]


def apphost_label(variable: str, method: str) -> str:
    labels = {
        "databaseServer": "PostgreSQL server",
        "database": "database",
        "cache": "Redis cache",
        "migrationService": "MigrationService",
        "apiService": "Admin.ApiService",
        "catalogApiService": "Catalog.ApiService",
    }
    if variable in labels:
        return labels[variable]
    label = method[3:] if method.startswith("Add") else variable
    return re.sub(r"(?<!^)([A-Z])", r" \1", label).replace(" Web", ".Web")


def ci_main_jobs_diagram() -> str:
    jobs = parse_workflow_jobs(ROOT / ".github/workflows/ci.yml")
    lines = [
        "```mermaid",
        "flowchart TB",
        "    trigger[Pull request, push to main, merge queue, or manual run]",
    ]
    for job_id, name, _ in jobs:
        lines.append(f"    {node_id(job_id)}[{name}]")
    for job_id, _, needs in jobs:
        if needs:
            for need in needs:
                lines.append(f"    {node_id(need)} --> {node_id(job_id)}")
        else:
            lines.append(f"    trigger --> {node_id(job_id)}")
    lines.append("```")
    return "\n".join(lines)


def ci_supplemental_workflows_diagram() -> str:
    lines = ["```mermaid", "flowchart LR", "    repo[Repository events]"]
    for workflow in sorted((ROOT / ".github/workflows").glob("*.yml")):
        if workflow.name == "ci.yml":
            continue
        name = workflow_name(workflow)
        lines.append(f"    {node_id(workflow.stem)}[{name}]")
        lines.append(f"    repo --> {node_id(workflow.stem)}")
    lines.append("```")
    return "\n".join(lines)


def parse_workflow_jobs(path: Path) -> list[tuple[str, str, list[str]]]:
    jobs: list[tuple[str, str, list[str]]] = []
    lines = path.read_text(encoding="utf-8").splitlines()
    in_jobs = False
    current_id = ""
    current_name = ""
    needs: list[str] = []
    needs_block = False

    def flush() -> None:
        nonlocal current_id, current_name, needs, needs_block
        if current_id:
            jobs.append((current_id, current_name or current_id, needs))
        current_id = ""
        current_name = ""
        needs = []
        needs_block = False

    for line in lines:
        if line == "jobs:":
            in_jobs = True
            continue
        if not in_jobs:
            continue
        job_match = re.match(r"^  ([a-zA-Z0-9_-]+):\s*$", line)
        if job_match:
            flush()
            current_id = job_match.group(1)
            continue
        if not current_id:
            continue
        name_match = re.match(r"^    name:\s+(.+)$", line)
        if name_match:
            current_name = name_match.group(1).strip('"')
            continue
        needs_inline = re.match(r"^    needs:\s+([a-zA-Z0-9_-]+)\s*$", line)
        if needs_inline:
            needs.append(needs_inline.group(1))
            continue
        if re.match(r"^    needs:\s*$", line):
            needs_block = True
            continue
        if needs_block:
            need_match = re.match(r"^      -\s+([a-zA-Z0-9_-]+)\s*$", line)
            if need_match:
                needs.append(need_match.group(1))
                continue
            needs_block = False
    flush()
    return jobs


def workflow_name(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        match = re.match(r"name:\s+(.+)$", line)
        if match:
            return match.group(1).strip('"')
    return path.stem


def format_edges(edges: list[tuple[str, str]]) -> list[str]:
    lines: list[str] = []
    for source, target in edges:
        lines.append(f"    {node_id(source)}[{source}] --> {node_id(target)}[{target}]")
    return lines or ["    empty[No project references]"]


def node_id(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", value)
    if cleaned and cleaned[0].isdigit():
        cleaned = f"n_{cleaned}"
    return cleaned


if __name__ == "__main__":
    sys.exit(main())
