#!/usr/bin/env python3

from __future__ import annotations

import argparse
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path


ROOT = Path.cwd()
MERMAID_START = "```mermaid"
MERMAID_END = "```"
FLOWCHART_TB = "flowchart TB"
FLOWCHART_LR = "flowchart LR"
JOB_HEADER = re.compile(r"^[ ]{2}(\w[\w-]*):\s*$")
JOB_NAME = re.compile(r"^[ ]{4}name:\s+(.+)$")
JOB_NEEDS = re.compile(r"^[ ]{4}needs:\s+(\w[\w-]*)\s*$")
JOB_NEEDS_BLOCK = re.compile(r"^[ ]{4}needs:\s*$")
JOB_NEED_ITEM = re.compile(r"^[ ]{6}-\s+(\w[\w-]*)\s*$")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Update generated architecture diagrams."
    )
    parser.add_argument(
        "--check", action="store_true", help="Fail when generated diagrams are stale."
    )
    args = parser.parse_args()

    changed = update_files(args.check, architecture_replacements())

    if args.check and changed:
        report_stale_files(changed)
        return 1

    report_changed_files(changed)
    return 0


def architecture_replacements() -> dict[str, str]:
    return {
        "project-dependencies": project_dependencies_diagram(),
        "sharedkernel-dependencies": sharedkernel_dependencies_diagram(),
        "apphost-resources": apphost_resources_diagram(),
        "ci-main-jobs": ci_main_jobs_diagram(),
        "ci-supplemental-workflows": ci_supplemental_workflows_diagram(),
    }


def update_files(check_only: bool, replacements: dict[str, str]) -> list[str]:
    changed = []
    for path in architecture_docs():
        updated = update_text(path.read_text(encoding="utf-8"), replacements)
        original = path.read_text(encoding="utf-8")
        if updated != original:
            changed.append(path.relative_to(ROOT).as_posix())
            if not check_only:
                write_text(path, updated)
    return changed


def architecture_docs() -> tuple[Path, ...]:
    return tuple(sorted((ROOT / "docs/architecture").glob("*.md")))


def update_text(text: str, replacements: dict[str, str]) -> str:
    for name, replacement in replacements.items():
        text = replace_generated_block(text, name, replacement)
    return text


def write_text(path: Path, content: str) -> None:
    with path.open("w", encoding="utf-8") as file:
        file.write(content)


def report_stale_files(changed: list[str]) -> None:
    print("Generated architecture diagrams are stale:", file=sys.stderr)
    for path in changed:
        print(f"- {path}", file=sys.stderr)
    print("Run: bash scripts/update-architecture-diagrams.sh", file=sys.stderr)


def report_changed_files(changed: list[str]) -> None:
    if changed:
        print("Updated generated architecture diagrams:")
        for path in changed:
            print(f"- {path}")
    else:
        print("Generated architecture diagrams are current.")


def replace_generated_block(text: str, name: str, replacement: str) -> str:
    pattern = re.compile(
        rf"<!-- generated:{re.escape(name)}:start -->.*?<!-- generated:{re.escape(name)}:end -->",
        re.DOTALL,
    )
    block = (
        f"<!-- generated:{name}:start -->\n"
        "<!-- Generated by scripts/update-architecture-diagrams.py. Do not edit by hand. -->\n\n"
        f"{replacement.rstrip()}\n"
        f"<!-- generated:{name}:end -->"
    )
    return pattern.sub(lambda _: block, text)


def project_dependencies_diagram() -> str:
    edges = project_reference_edges(
        lambda path: path.parts[0] == "src" and "SharedKernel" not in path.parts
    )
    return mermaid_diagram(FLOWCHART_TB, format_edges(edges))


def sharedkernel_dependencies_diagram() -> str:
    edges = project_reference_edges(
        lambda path: path.parts[:2] == ("src", "SharedKernel")
    )
    return mermaid_diagram(FLOWCHART_TB, format_edges(edges))


def project_reference_edges(include_project) -> list[tuple[str, str]]:
    edges: list[tuple[str, str]] = []
    for project in sorted(ROOT.glob("**/*.csproj")):
        relative = project.relative_to(ROOT)
        if not include_project(relative):
            continue
        source = project.stem
        root = ET.parse(project).getroot()
        for reference in root.findall(".//ProjectReference"):
            include = reference.attrib.get("Include")
            if not include:
                continue
            target = (project.parent / include).resolve().stem
            edges.append((source, target))
    return sorted(set(edges))


def apphost_resources_diagram() -> str:
    path = ROOT / "src/ViajantesTurismo.AppHost/AppHost.cs"
    variables: dict[str, str] = {}
    edges: list[tuple[str, str]] = []
    assignment = re.compile(r"var\s+(\w+)\s+=\s+([\w.]+)\.(\w+)\(([^)]*)\);")

    for line in path.read_text(encoding="utf-8").splitlines():
        match = assignment.search(line)
        if not match:
            continue
        variable, receiver, method, args = match.groups()
        if method == "CreateBuilder":
            continue
        variables[variable] = apphost_label(variable, method)
        receiver_name = receiver.rsplit(".", 1)[-1]
        if receiver_name in variables:
            edges.append((variable, receiver_name))
        for arg in parse_apphost_args(args):
            if arg in variables:
                edges.append((variable, arg))

    invocation = re.compile(r"builder\.(Add\w+)\(([^)]*)\);")
    for line in path.read_text(encoding="utf-8").splitlines():
        match = invocation.search(line)
        if not match or "var " in line:
            continue
        method, args = match.groups()
        node = method[3:]
        variables[node] = apphost_label(node, method)
        for arg in parse_apphost_args(args):
            if arg in variables:
                edges.append((node, arg))

    lines: list[str] = []
    for key, label in sorted(variables.items(), key=lambda item: item[1]):
        lines.append(f"    {node_id(key)}[{label}]")
    for source, target in sorted(set(edges)):
        lines.append(f"    {node_id(source)} --> {node_id(target)}")
    return mermaid_diagram(FLOWCHART_LR, lines)


def parse_apphost_args(args: str) -> list[str]:
    return [arg.strip() for arg in args.split(",") if re.fullmatch(r"\w+", arg.strip())]


def apphost_label(variable: str, method: str) -> str:
    labels = {
        "databaseServer": "PostgreSQL server",
        "database": "database",
        "cache": "Redis cache",
        "migrationService": "MigrationService",
        "apiService": "Admin.ApiService",
        "catalogApiService": "Catalog.ApiService",
    }
    if variable in labels:
        return labels[variable]
    label = method[3:] if method.startswith("Add") else variable
    return re.sub(r"(?<!^)([A-Z])", r" \1", label).replace(" Web", ".Web")


def ci_main_jobs_diagram() -> str:
    jobs = parse_workflow_jobs(ROOT / ".github/workflows/ci.yml")
    lines = ["    trigger[Pull request, push to main, merge queue, or manual run]"]
    for job_id, name, _ in jobs:
        lines.append(f"    {node_id(job_id)}[{name}]")
    for job_id, _, needs in jobs:
        if needs:
            for need in needs:
                lines.append(f"    {node_id(need)} --> {node_id(job_id)}")
        else:
            lines.append(f"    trigger --> {node_id(job_id)}")
    return mermaid_diagram(FLOWCHART_TB, lines)


def ci_supplemental_workflows_diagram() -> str:
    lines = ["    repo[Repository events]"]
    for workflow in sorted((ROOT / ".github/workflows").glob("*.yml")):
        if workflow.name == "ci.yml":
            continue
        name = workflow_name(workflow)
        lines.append(f"    {node_id(workflow.stem)}[{name}]")
        lines.append(f"    repo --> {node_id(workflow.stem)}")
    return mermaid_diagram(FLOWCHART_LR, lines)


def parse_workflow_jobs(path: Path) -> list[tuple[str, str, list[str]]]:
    jobs: list[tuple[str, str, list[str]]] = []
    current_id = ""
    current_name = ""
    needs: list[str] = []
    needs_block = False

    def flush() -> None:
        nonlocal current_id, current_name, needs, needs_block
        if current_id:
            jobs.append((current_id, current_name or current_id, needs))
        current_id = ""
        current_name = ""
        needs = []
        needs_block = False

    for line in workflow_job_lines(path):
        job_match = JOB_HEADER.match(line)
        if job_match:
            flush()
            current_id = job_match.group(1)
            continue
        if not current_id:
            continue
        name_match = JOB_NAME.match(line)
        if name_match:
            current_name = name_match.group(1).strip('"')
            continue
        needs_inline = JOB_NEEDS.match(line)
        if needs_inline:
            needs.append(needs_inline.group(1))
            continue
        if JOB_NEEDS_BLOCK.match(line):
            needs_block = True
            continue
        if needs_block:
            needs_block = append_need(line, needs)
    flush()
    return jobs


def workflow_job_lines(path: Path):
    lines = path.read_text(encoding="utf-8").splitlines()
    try:
        start = lines.index("jobs:") + 1
    except ValueError:
        return []
    return lines[start:]


def append_need(line: str, needs: list[str]) -> bool:
    need_match = JOB_NEED_ITEM.match(line)
    if not need_match:
        return False
    needs.append(need_match.group(1))
    return True


def workflow_name(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        match = re.match(r"name:\s+(.+)$", line)
        if match:
            return match.group(1).strip('"')
    return path.stem


def format_edges(edges: list[tuple[str, str]]) -> list[str]:
    lines: list[str] = []
    for source, target in edges:
        lines.append(f"    {node_id(source)}[{source}] --> {node_id(target)}[{target}]")
    return lines or ["    empty[No project references]"]


def mermaid_diagram(flowchart: str, body: list[str]) -> str:
    return "\n".join([MERMAID_START, flowchart, *body, MERMAID_END])


def node_id(value: str) -> str:
    cleaned = re.sub(r"\W", "_", value)
    if cleaned and cleaned[0].isdigit():
        cleaned = f"n_{cleaned}"
    return cleaned


if __name__ == "__main__":
    sys.exit(main())
