using System.Text;

namespace SharedKernel.Mediator.SourceGenerator;

/// <summary>
/// Emits the generated mediator shell owned by the consumer compilation.
/// </summary>
internal static class AppMediatorEmitter
{
    public static string Emit()
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine();
        builder.AppendLine("namespace SharedKernel.Mediator;");
        builder.AppendLine();
        builder.AppendLine("public sealed partial class AppMediator : IMediator");
        builder.AppendLine("{");
        builder.AppendLine("    public AppMediator(global::System.IServiceProvider services)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(services);");
        builder.AppendLine();
        builder.AppendLine("        Services = services;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    internal global::System.IServiceProvider Services { get; }");
        builder.AppendLine();
        builder.AppendLine("    public global::System.Threading.Tasks.ValueTask<TResponse> Send<TResponse>(");
        builder.AppendLine("        global::SharedKernel.Mediator.IRequest<TResponse> request,");
        builder.AppendLine("        global::System.Threading.CancellationToken ct)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(request);");
        builder.AppendLine();
        builder.AppendLine("        throw new global::System.NotSupportedException(\"Generated request dispatch is not available yet.\");");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public global::System.Threading.Tasks.ValueTask Publish<TNotification>(");
        builder.AppendLine("        TNotification notification,");
        builder.AppendLine("        global::System.Threading.CancellationToken ct)");
        builder.AppendLine("        where TNotification : global::SharedKernel.Mediator.INotification");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(notification);");
        builder.AppendLine();
        builder.AppendLine("        throw new global::System.NotSupportedException(\"Generated notification dispatch is not available yet.\");");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }
}
