using System.Text;

namespace SharedKernel.Mediator.SourceGenerator;

/// <summary>
/// Emits the generated mediator shell owned by the consumer compilation.
/// </summary>
internal static class AppMediatorEmitter
{
    public static string Emit(DiscoveryModel model)
    {
        var builder = new StringBuilder();
        GeneratedXmlDocumentationEmitter.AppendAutoGeneratedHeader(builder);
        builder.AppendLine("namespace SharedKernel.Mediator;");
        builder.AppendLine();
        GeneratedXmlDocumentationEmitter.AppendSummary(
            builder,
            string.Empty,
            "Provides the generated mediator shell owned by the consumer compilation.");
        builder.AppendLine("public sealed partial class AppMediator : IMediator");
        builder.AppendLine("{");
        GeneratedXmlDocumentationEmitter.AppendSummary(
            builder,
            "    ",
            "Initializes a new instance of the <see cref=\"AppMediator\"/> class.");
        GeneratedXmlDocumentationEmitter.AppendParam(
            builder,
            "    ",
            "services",
            "The scoped service provider used by generated mediator code.");
        builder.AppendLine("    public AppMediator(global::System.IServiceProvider services)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(services);");
        builder.AppendLine();
        builder.AppendLine("        Services = services;");
        builder.AppendLine("    }");
        builder.AppendLine();
        GeneratedXmlDocumentationEmitter.AppendSummary(
            builder,
            "    ",
            "Gets the scoped service provider used by generated mediator code.");
        builder.AppendLine("    internal global::System.IServiceProvider Services { get; }");
        builder.AppendLine();

        for (var requestIndex = 0; requestIndex < model.Requests.Length; requestIndex++)
        {
            EmitTypedSendOverload(builder, model.Requests[requestIndex], requestIndex);
        }

        for (var streamRequestIndex = 0; streamRequestIndex < model.StreamRequests.Length; streamRequestIndex++)
        {
            EmitTypedCreateStreamOverload(builder, model.StreamRequests[streamRequestIndex]);
        }

        builder.AppendLine();
        GeneratedXmlDocumentationEmitter.AppendInheritdoc(builder, "    ");
        builder.AppendLine("    public global::System.Threading.Tasks.ValueTask<TResponse> Send<TResponse>(");
        builder.AppendLine("        global::SharedKernel.Mediator.IRequest<TResponse> request,");
        builder.AppendLine("        global::System.Threading.CancellationToken ct)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(request);");
        builder.AppendLine();
        builder.AppendLine("        return GeneratedDispatch.Send<TResponse>(this, request, ct);");
        builder.AppendLine("    }");
        builder.AppendLine();
        GeneratedXmlDocumentationEmitter.AppendSummary(
            builder,
            "    ",
            "Creates a stream request instance through the generated stream-dispatch path.");
        GeneratedXmlDocumentationEmitter.AppendParam(
            builder,
            "    ",
            "request",
            "The stream request instance to dispatch.");
        GeneratedXmlDocumentationEmitter.AppendParam(
            builder,
            "    ",
            "ct",
            "The cancellation token for the operation.");
        GeneratedXmlDocumentationEmitter.AppendReturns(
            builder,
            "    ",
            "The produced response stream.");
        builder.AppendLine("    public global::System.Collections.Generic.IAsyncEnumerable<TResponse> CreateStream<TResponse>(");
        builder.AppendLine("        global::SharedKernel.Mediator.IStreamRequest<TResponse> request,");
        builder.AppendLine("        global::System.Threading.CancellationToken ct)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(request);");
        builder.AppendLine();
        builder.AppendLine("        return GeneratedDispatch.CreateStream<TResponse>(this, request, ct);");
        builder.AppendLine("    }");
        builder.AppendLine();
        GeneratedXmlDocumentationEmitter.AppendSummary(
            builder,
            "    ",
            "Sends a request instance through the generated object-dispatch path.");
        GeneratedXmlDocumentationEmitter.AppendParam(
            builder,
            "    ",
            "request",
            "The boxed request instance to dispatch.");
        GeneratedXmlDocumentationEmitter.AppendParam(
            builder,
            "    ",
            "ct",
            "The cancellation token for the operation.");
        GeneratedXmlDocumentationEmitter.AppendReturns(
            builder,
            "    ",
            "The boxed response value produced by the generated dispatch path.");
        builder.AppendLine("    public global::System.Threading.Tasks.ValueTask<object?> SendObject(");
        builder.AppendLine("        object request,");
        builder.AppendLine("        global::System.Threading.CancellationToken ct)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(request);");
        builder.AppendLine();
        builder.AppendLine("        return GeneratedDispatch.SendObject(this, request, ct);");
        builder.AppendLine("    }");
        builder.AppendLine();
        GeneratedXmlDocumentationEmitter.AppendInheritdoc(builder, "    ");
        builder.AppendLine("    public global::System.Threading.Tasks.ValueTask Publish<TNotification>(");
        builder.AppendLine("        TNotification notification,");
        builder.AppendLine("        global::System.Threading.CancellationToken ct)");
        builder.AppendLine("        where TNotification : global::SharedKernel.Mediator.INotification");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(notification);");
        builder.AppendLine();
        builder.AppendLine("        return GeneratedDispatch.Publish(this, notification, ct);");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static void EmitTypedSendOverload(StringBuilder builder, RequestDescriptor request, int requestIndex)
    {
        var accessibleHandlers = request.Handlers
            .Where(static handler => handler.IsAccessibleToGeneratedMediator && handler.HasCompatibleHandleMethod)
            .ToArray();

        builder.AppendLine();
        GeneratedXmlDocumentationEmitter.AppendSummary(
            builder,
            "    ",
            $"Sends a <see cref=\"{request.MetadataName}\"/> request through the generated mediator dispatch path.");
        GeneratedXmlDocumentationEmitter.AppendParam(
            builder,
            "    ",
            "request",
            "The request instance to dispatch.");
        GeneratedXmlDocumentationEmitter.AppendParam(
            builder,
            "    ",
            "ct",
            "The cancellation token for the operation.");
        GeneratedXmlDocumentationEmitter.AppendReturns(
            builder,
            "    ",
            "The produced response value.");
        builder.Append("    public global::System.Threading.Tasks.ValueTask<")
            .Append(request.Response.MetadataName)
            .Append("> Send(")
            .Append(request.MetadataName)
            .AppendLine(" request,");
        builder.AppendLine("        global::System.Threading.CancellationToken ct)");
        builder.AppendLine("    {");

        if (!request.IsValueType)
        {
            builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(request);");
            builder.AppendLine();
        }

        switch (accessibleHandlers.Length)
        {
            case 0:
                builder.Append("        return GeneratedDispatch.ThrowNoHandler<")
                    .Append(request.Response.MetadataName)
                    .AppendLine(">(request);");
                break;
            case 1:
                if (request.Pipelines.Length == 0)
                {
                    builder.Append("        var handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<")
                        .Append(accessibleHandlers[0].MetadataName)
                        .AppendLine(">(Services);");
                    builder.AppendLine();
                    builder.AppendLine("        return handler.Handle(request, ct);");
                }
                else
                {
                    builder.Append("        return GeneratedPipelines.Invoke_")
                        .Append(requestIndex.ToString("D4", global::System.Globalization.CultureInfo.InvariantCulture))
                        .AppendLine("(this, request, ct);");
                }
                break;
            default:
                builder.Append("        return GeneratedDispatch.ThrowAmbiguousHandlers<")
                    .Append(request.Response.MetadataName)
                    .Append(">(request, ")
                    .Append(accessibleHandlers.Length)
                    .AppendLine(");");
                break;
        }

        builder.AppendLine("    }");
    }

    private static void EmitTypedCreateStreamOverload(StringBuilder builder, StreamRequestDescriptor streamRequest)
    {
        var accessibleHandlers = streamRequest.Handlers
            .Where(static handler => handler.IsAccessibleToGeneratedMediator)
            .ToArray();

        builder.AppendLine();
        GeneratedXmlDocumentationEmitter.AppendSummary(
            builder,
            "    ",
            $"Creates a <see cref=\"{streamRequest.MetadataName}\"/> stream through the generated mediator dispatch path.");
        GeneratedXmlDocumentationEmitter.AppendParam(
            builder,
            "    ",
            "request",
            "The stream request instance to dispatch.");
        GeneratedXmlDocumentationEmitter.AppendParam(
            builder,
            "    ",
            "ct",
            "The cancellation token for the operation.");
        GeneratedXmlDocumentationEmitter.AppendReturns(
            builder,
            "    ",
            "The produced response stream.");
        builder.Append("    public global::System.Collections.Generic.IAsyncEnumerable<")
            .Append(streamRequest.ItemResponse.MetadataName)
            .Append("> CreateStream(")
            .Append(streamRequest.MetadataName)
            .AppendLine(" request,");
        builder.AppendLine("        global::System.Threading.CancellationToken ct)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(request);");
        builder.AppendLine();

        switch (accessibleHandlers.Length)
        {
            case 0:
                builder.Append("        return GeneratedDispatch.ThrowNoStreamHandler<")
                    .Append(streamRequest.ItemResponse.MetadataName)
                    .AppendLine(">(request);");
                break;
            case 1:
                builder.Append("        var handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<")
                    .Append(accessibleHandlers[0].MetadataName)
                    .AppendLine(">(Services);");
                builder.AppendLine();
                builder.AppendLine("        return handler.Handle(request, ct);");
                break;
            default:
                builder.Append("        return GeneratedDispatch.ThrowAmbiguousStreamHandlers<")
                    .Append(streamRequest.ItemResponse.MetadataName)
                    .Append(">(request, ")
                    .Append(accessibleHandlers.Length)
                    .AppendLine(");");
                break;
        }

        builder.AppendLine("    }");
    }
}
