using System.Text;

namespace SharedKernel.Mediator.SourceGenerator;

/// <summary>
/// Emits the generated mediator shell owned by the consumer compilation.
/// </summary>
internal static class AppMediatorEmitter
{
    public static string Emit(DiscoveryModel model)
    {
        var builder = new StringBuilder();
        GeneratedXmlDocumentationEmitter.AppendAutoGeneratedHeader(builder);
        builder.AppendLine("namespace SharedKernel.Mediator;");
        builder.AppendLine();
        GeneratedXmlDocumentationEmitter.AppendSummary(
            builder,
            string.Empty,
            "Provides the generated mediator shell owned by the consumer compilation.");
        builder.AppendLine("public sealed partial class AppMediator : IMediator");
        builder.AppendLine("{");
        GeneratedXmlDocumentationEmitter.AppendSummary(
            builder,
            "    ",
            "Initializes a new instance of the <see cref=\"AppMediator\"/> class.");
        GeneratedXmlDocumentationEmitter.AppendParam(
            builder,
            "    ",
            "services",
            "The scoped service provider used by generated mediator code.");
        builder.AppendLine("    public AppMediator(global::System.IServiceProvider services)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(services);");
        builder.AppendLine();
        builder.AppendLine("        Services = services;");
        builder.AppendLine("    }");
        builder.AppendLine();
        GeneratedXmlDocumentationEmitter.AppendSummary(
            builder,
            "    ",
            "Gets the scoped service provider used by generated mediator code.");
        builder.AppendLine("    internal global::System.IServiceProvider Services { get; }");
        builder.AppendLine();

        foreach (var request in model.Requests)
        {
            EmitTypedSendOverload(builder, request);
        }

        builder.AppendLine();
        GeneratedXmlDocumentationEmitter.AppendInheritdoc(builder, "    ");
        builder.AppendLine("    public global::System.Threading.Tasks.ValueTask<TResponse> Send<TResponse>(");
        builder.AppendLine("        global::SharedKernel.Mediator.IRequest<TResponse> request,");
        builder.AppendLine("        global::System.Threading.CancellationToken ct)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(request);");
        builder.AppendLine();
        builder.AppendLine("        return GeneratedDispatch.Send<TResponse>(this, request, ct);");
        builder.AppendLine("    }");
        builder.AppendLine();
        GeneratedXmlDocumentationEmitter.AppendInheritdoc(builder, "    ");
        builder.AppendLine("    public global::System.Threading.Tasks.ValueTask Publish<TNotification>(");
        builder.AppendLine("        TNotification notification,");
        builder.AppendLine("        global::System.Threading.CancellationToken ct)");
        builder.AppendLine("        where TNotification : global::SharedKernel.Mediator.INotification");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(notification);");
        builder.AppendLine();
        builder.AppendLine("        throw new global::System.NotSupportedException(\"Generated notification dispatch is not available yet.\");");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine();
        EmitGeneratedDispatch(builder, model.Requests);

        return builder.ToString();
    }

    private static void EmitTypedSendOverload(StringBuilder builder, RequestDescriptor request)
    {
        var accessibleHandlers = request.Handlers
            .Where(static handler => handler.IsAccessibleToGeneratedMediator && handler.HasCompatibleHandleMethod)
            .ToArray();

        builder.AppendLine();
        GeneratedXmlDocumentationEmitter.AppendSummary(
            builder,
            "    ",
            $"Sends a <see cref=\"{request.MetadataName}\"/> request through the generated mediator dispatch path.");
        GeneratedXmlDocumentationEmitter.AppendParam(
            builder,
            "    ",
            "request",
            "The request instance to dispatch.");
        GeneratedXmlDocumentationEmitter.AppendParam(
            builder,
            "    ",
            "ct",
            "The cancellation token for the operation.");
        GeneratedXmlDocumentationEmitter.AppendReturns(
            builder,
            "    ",
            "The produced response value.");
        builder.Append("    public global::System.Threading.Tasks.ValueTask<")
            .Append(request.Response.MetadataName)
            .Append("> Send(")
            .Append(request.MetadataName)
            .AppendLine(" request,");
        builder.AppendLine("        global::System.Threading.CancellationToken ct)");
        builder.AppendLine("    {");

        if (!request.IsValueType)
        {
            builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(request);");
            builder.AppendLine();
        }

        switch (accessibleHandlers.Length)
        {
            case 0:
                builder.Append("        return GeneratedDispatch.ThrowNoHandler<")
                    .Append(request.Response.MetadataName)
                    .AppendLine(">(request);");
                break;
            case 1:
                builder.Append("        var handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<")
                    .Append(accessibleHandlers[0].MetadataName)
                    .AppendLine(">(Services);");
                builder.AppendLine();
                builder.AppendLine("        return handler.Handle(request, ct);");
                break;
            default:
                builder.Append("        return GeneratedDispatch.ThrowAmbiguousHandlers<")
                    .Append(request.Response.MetadataName)
                    .Append(">(request, ")
                    .Append(accessibleHandlers.Length)
                    .AppendLine(");");
                break;
        }

        builder.AppendLine("    }");
    }

    private static void EmitGeneratedDispatch(StringBuilder builder, IEnumerable<RequestDescriptor> requests)
    {
        builder.AppendLine("internal static class GeneratedDispatch");
        builder.AppendLine("{");
        builder.AppendLine("    public static global::System.Threading.Tasks.ValueTask<TResponse> Send<TResponse>(");
        builder.AppendLine("        AppMediator mediator,");
        builder.AppendLine("        global::SharedKernel.Mediator.IRequest<TResponse> request,");
        builder.AppendLine("        global::System.Threading.CancellationToken ct)");
        builder.AppendLine("    {");
        builder.AppendLine("        return request switch");
        builder.AppendLine("        {");

        foreach (var request in requests)
        {
            builder.Append("            ")
                .Append(request.MetadataName)
                .Append(" typed => Cast<")
                .Append(request.Response.MetadataName)
                .Append(", TResponse>(mediator.Send(typed, ct)),")
                .AppendLine();
        }

        builder.AppendLine("            _ => ThrowNoHandler<TResponse>(request),");
        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public static async global::System.Threading.Tasks.ValueTask<TTarget> Cast<TSource, TTarget>(");
        builder.AppendLine("        global::System.Threading.Tasks.ValueTask<TSource> source)");
        builder.AppendLine("    {");
        builder.AppendLine("        var result = await source.ConfigureAwait(false);");
        builder.AppendLine();
        builder.AppendLine("        if (result is TTarget typed)");
        builder.AppendLine("        {");
        builder.AppendLine("            return typed;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        return ThrowInvalidResponseCast<TSource, TTarget>();");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public static global::System.Threading.Tasks.ValueTask<TResponse> ThrowNoHandler<TResponse>(");
        builder.AppendLine("        global::SharedKernel.Mediator.IRequest<TResponse> request)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(request);");
        builder.AppendLine();
        builder.AppendLine("        throw new global::System.NotSupportedException($\"Generated request dispatch is not available for request type '{request.GetType().FullName}'.\");");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public static global::System.Threading.Tasks.ValueTask<TResponse> ThrowAmbiguousHandlers<TResponse>(");
        builder.AppendLine("        global::SharedKernel.Mediator.IRequest<TResponse> request,");
        builder.AppendLine("        int handlerCount)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(request);");
        builder.AppendLine();
        builder.AppendLine("        throw new global::System.InvalidOperationException($\"Generated request dispatch found {handlerCount} accessible handlers for request type '{request.GetType().FullName}'.\");");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public static TTarget ThrowInvalidResponseCast<TSource, TTarget>()");
        builder.AppendLine("    {");
        builder.AppendLine("        throw new global::System.InvalidOperationException($\"Generated request dispatch returned '{typeof(TSource).FullName}' when '{typeof(TTarget).FullName}' was expected.\");");
        builder.AppendLine("    }");
        builder.AppendLine("}");
    }
}
