namespace SharedKernel.Mediator.SourceGenerator;

/// <summary>
/// Emits generated Microsoft.Extensions.DependencyInjection registrations from discovery data.
/// </summary>
internal static class DependencyInjectionEmitter
{
    private const string AddTransientMethodName = "AddTransient";

    public static string Emit(DiscoveryModel model)
    {
        var writer = new IndentedCodeWriter();
        var emittedRegistrationKeys = new HashSet<string>(StringComparer.Ordinal);

        GeneratedXmlDocumentationEmitter.AppendAutoGeneratedHeader(writer);
        writer.Line("using Microsoft.Extensions.DependencyInjection;");
        writer.Line();
        writer.Line("namespace SharedKernel.Mediator;");
        writer.Line();
        GeneratedXmlDocumentationEmitter.AppendSummary(
            writer,
            "Provides the generated dependency injection registrations for mediator services.");
        writer.Line("public static partial class SharedKernelMediatorServiceCollectionExtensions");
        writer.Line("{");
        writer.Indent();
        GeneratedXmlDocumentationEmitter.AppendSummary(
            writer,
            "Adds the generated mediator registrations to the service collection.");
        GeneratedXmlDocumentationEmitter.AppendParam(writer, "services", "The service collection to populate.");
        GeneratedXmlDocumentationEmitter.AppendReturns(writer, "The same service collection so calls can be chained.");
        writer.Line("public static IServiceCollection AddSharedKernelMediator(this IServiceCollection services)");
        writer.Line("{");
        writer.Indent();
        writer.Line("global::System.ArgumentNullException.ThrowIfNull(services);");
        writer.Line("services.AddScoped<AppMediator>();");
        writer.Line("services.AddScoped<ISender>(static sp => sp.GetRequiredService<AppMediator>());");
        writer.Line("services.AddScoped<IPublisher>(static sp => sp.GetRequiredService<AppMediator>());");
        writer.Line("services.AddScoped<IMediator>(static sp => sp.GetRequiredService<AppMediator>());");
        writer.Line();

        var emittedRequestRegistrations = EmitRequestRegistrations(writer, model.Requests, emittedRegistrationKeys);
        var emittedNotificationRegistrations = EmitNotificationRegistrations(
            writer,
            model.Notifications,
            emittedRequestRegistrations,
            emittedRegistrationKeys);
        var emittedStreamRegistrations = EmitStreamRegistrations(
            writer,
            model.StreamRequests,
            emittedRequestRegistrations || emittedNotificationRegistrations,
            emittedRegistrationKeys);

        if (emittedRequestRegistrations || emittedNotificationRegistrations || emittedStreamRegistrations)
        {
            writer.Line();
        }

        writer.Line("return services;");
        writer.Unindent();
        writer.Line("}");
        writer.Unindent();
        writer.Line("}");

        return writer.ToString();
    }

    private static bool EmitRequestRegistrations(
        IndentedCodeWriter writer,
        IEnumerable<RequestDescriptor> requests,
        HashSet<string> emittedRegistrationKeys)
    {
        var emittedAny = false;

        foreach (var request in requests)
        {
            foreach (var handler in request.Handlers.Where(static handler => handler.IsAccessibleToGeneratedMediator && handler.HasCompatibleHandleMethod))
            {
                EmitRegistration(
                    writer,
                    AddTransientMethodName,
                    handler.MetadataName,
                    MediatorGenerationNames.GetHandlerServiceType(handler),
                    emittedRegistrationKeys);
                emittedAny = true;
            }

            foreach (var pipeline in request.Pipelines.Where(static pipeline => pipeline.IsAccessibleToGeneratedMediator))
            {
                EmitRegistration(
                    writer,
                    AddTransientMethodName,
                    pipeline.MetadataName,
                    MediatorGenerationNames.GetPipelineServiceType(
                        pipeline.IsStream,
                        request.MetadataName,
                        request.Response.MetadataName),
                    emittedRegistrationKeys);
                emittedAny = true;
            }
        }

        return emittedAny;
    }

    private static bool EmitNotificationRegistrations(
        IndentedCodeWriter writer,
        IEnumerable<NotificationDescriptor> notifications,
        bool hasPriorRegistrations,
        HashSet<string> emittedRegistrationKeys)
    {
        var emittedAny = false;

        foreach (var notification in notifications)
        {
            if (!emittedAny && hasPriorRegistrations)
            {
                writer.Line();
            }

            foreach (var handler in notification.Handlers.Where(static handler => handler.IsAccessibleToGeneratedMediator))
            {
                EmitRegistration(
                    writer,
                    AddTransientMethodName,
                    handler.MetadataName,
                    MediatorGenerationNames.GetNotificationHandlerServiceType(notification.MetadataName),
                    emittedRegistrationKeys);
                emittedAny = true;
            }
        }

        return emittedAny;
    }

    private static bool EmitStreamRegistrations(
        IndentedCodeWriter writer,
        IEnumerable<StreamRequestDescriptor> streamRequests,
        bool hasPriorRegistrations,
        HashSet<string> emittedRegistrationKeys)
    {
        var emittedAny = false;

        foreach (var streamRequest in streamRequests)
        {
            if (!emittedAny && hasPriorRegistrations)
            {
                writer.Line();
            }

            foreach (var handler in streamRequest.Handlers.Where(static handler => handler.IsAccessibleToGeneratedMediator))
            {
                EmitRegistration(
                    writer,
                    AddTransientMethodName,
                    handler.MetadataName,
                    MediatorGenerationNames.GetStreamHandlerServiceType(streamRequest.MetadataName, streamRequest.ItemResponse.MetadataName),
                    emittedRegistrationKeys);
                emittedAny = true;
            }

            foreach (var pipeline in streamRequest.Pipelines.Where(static pipeline => pipeline.IsAccessibleToGeneratedMediator))
            {
                EmitRegistration(
                    writer,
                    AddTransientMethodName,
                    pipeline.MetadataName,
                    MediatorGenerationNames.GetPipelineServiceType(
                        pipeline.IsStream,
                        streamRequest.MetadataName,
                        streamRequest.ItemResponse.MetadataName),
                    emittedRegistrationKeys);
                emittedAny = true;
            }
        }

        return emittedAny;
    }

    private static void EmitRegistration(
        IndentedCodeWriter writer,
        string methodName,
        string implementationType,
        string serviceType,
        HashSet<string> emittedRegistrationKeys)
    {
        var selfRegistrationKey = $"{implementationType}|{implementationType}";
        if (emittedRegistrationKeys.Add(selfRegistrationKey))
        {
            writer.Line($"services.{methodName}<{implementationType}>();");
        }

        var serviceRegistrationKey = $"{serviceType}|{implementationType}";
        if (emittedRegistrationKeys.Add(serviceRegistrationKey))
        {
            writer.Line($"services.{methodName}<{serviceType}, {implementationType}>();");
        }
    }
}
