using System.Text;

namespace SharedKernel.Mediator.SourceGenerator;

/// <summary>
/// Emits generated Microsoft.Extensions.DependencyInjection registrations from discovery data.
/// </summary>
internal static class DependencyInjectionEmitter
{
    private const string AddTransientMethodName = "AddTransient";

    public static string Emit(DiscoveryModel model)
    {
        var builder = new StringBuilder();
        var emittedRegistrationKeys = new HashSet<string>(StringComparer.Ordinal);
        GeneratedXmlDocumentationEmitter.AppendAutoGeneratedHeader(builder);
        builder.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        builder.AppendLine();
        builder.AppendLine("namespace SharedKernel.Mediator;");
        builder.AppendLine();
        GeneratedXmlDocumentationEmitter.AppendSummary(
            builder,
            string.Empty,
            "Provides the generated dependency injection registrations for mediator services.");
        builder.AppendLine("public static partial class SharedKernelMediatorServiceCollectionExtensions");
        builder.AppendLine("{");
        GeneratedXmlDocumentationEmitter.AppendSummary(
            builder,
            "    ",
            "Adds the generated mediator registrations to the service collection.");
        GeneratedXmlDocumentationEmitter.AppendParam(
            builder,
            "    ",
            "services",
            "The service collection to populate.");
        GeneratedXmlDocumentationEmitter.AppendReturns(
            builder,
            "    ",
            "The same service collection so calls can be chained.");
        builder.AppendLine("    public static IServiceCollection AddSharedKernelMediator(this IServiceCollection services)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(services);");
        builder.AppendLine("        services.AddScoped<AppMediator>();");
        builder.AppendLine("        services.AddScoped<ISender>(static sp => sp.GetRequiredService<AppMediator>());");
        builder.AppendLine("        services.AddScoped<IPublisher>(static sp => sp.GetRequiredService<AppMediator>());");
        builder.AppendLine("        services.AddScoped<IMediator>(static sp => sp.GetRequiredService<AppMediator>());");
        builder.AppendLine();

        var emittedRequestRegistrations = EmitRequestRegistrations(builder, model.Requests, emittedRegistrationKeys);
        var emittedNotificationRegistrations = EmitNotificationRegistrations(builder, model.Notifications, emittedRequestRegistrations, emittedRegistrationKeys);
        var emittedStreamRegistrations = EmitStreamRegistrations(
            builder,
            model.StreamRequests,
            emittedRequestRegistrations || emittedNotificationRegistrations,
            emittedRegistrationKeys);

        if (emittedRequestRegistrations || emittedNotificationRegistrations || emittedStreamRegistrations)
        {
            builder.AppendLine();
        }

        builder.AppendLine("        return services;");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static bool EmitRequestRegistrations(
        StringBuilder builder,
        IEnumerable<RequestDescriptor> requests,
        HashSet<string> emittedRegistrationKeys)
    {
        var emittedAny = false;

        foreach (var request in requests)
        {
            foreach (var handler in request.Handlers.Where(static handler => handler.IsAccessibleToGeneratedMediator && handler.HasCompatibleHandleMethod))
            {
                EmitRegistration(
                    builder,
                    AddTransientMethodName,
                    handler.MetadataName,
                    GetHandlerServiceType(request, handler),
                    emittedRegistrationKeys);
                emittedAny = true;
            }

            foreach (var pipeline in request.Pipelines.Where(static pipeline => pipeline.IsAccessibleToGeneratedMediator))
            {
                EmitRegistration(
                    builder,
                    AddTransientMethodName,
                    pipeline.MetadataName,
                    $"global::SharedKernel.Mediator.IPipelineBehavior<{request.MetadataName}, {request.Response.MetadataName}>",
                    emittedRegistrationKeys);
                emittedAny = true;
            }
        }

        return emittedAny;
    }

    private static bool EmitNotificationRegistrations(
        StringBuilder builder,
        IEnumerable<NotificationDescriptor> notifications,
        bool hasPriorRegistrations,
        HashSet<string> emittedRegistrationKeys)
    {
        var emittedAny = false;

        foreach (var notification in notifications)
        {
            if (!emittedAny && hasPriorRegistrations)
            {
                builder.AppendLine();
            }

            foreach (var handler in notification.Handlers.Where(static handler => handler.IsAccessibleToGeneratedMediator))
            {
                EmitRegistration(
                    builder,
                    AddTransientMethodName,
                    handler.MetadataName,
                    $"global::SharedKernel.Mediator.INotificationHandler<{notification.MetadataName}>",
                    emittedRegistrationKeys);
                emittedAny = true;
            }
        }

        return emittedAny;
    }

    private static bool EmitStreamRegistrations(
        StringBuilder builder,
        IEnumerable<StreamRequestDescriptor> streamRequests,
        bool hasPriorRegistrations,
        HashSet<string> emittedRegistrationKeys)
    {
        var emittedAny = false;

        foreach (var streamRequest in streamRequests)
        {
            if (!emittedAny && hasPriorRegistrations)
            {
                builder.AppendLine();
            }

            foreach (var handler in streamRequest.Handlers.Where(static handler => handler.IsAccessibleToGeneratedMediator))
            {
                EmitRegistration(
                    builder,
                    AddTransientMethodName,
                    handler.MetadataName,
                    $"global::SharedKernel.Mediator.IStreamRequestHandler<{streamRequest.MetadataName}, {streamRequest.ItemResponse.MetadataName}>",
                    emittedRegistrationKeys);
                emittedAny = true;
            }
        }

        return emittedAny;
    }

    private static void EmitRegistration(
        StringBuilder builder,
        string methodName,
        string implementationType,
        string serviceType,
        HashSet<string> emittedRegistrationKeys)
    {
        var selfRegistrationKey = $"{implementationType}|{implementationType}";
        if (emittedRegistrationKeys.Add(selfRegistrationKey))
        {
            builder.Append("        services.").Append(methodName).Append('<').Append(implementationType).AppendLine(">();");
        }

        var serviceRegistrationKey = $"{serviceType}|{implementationType}";
        if (emittedRegistrationKeys.Add(serviceRegistrationKey))
        {
            builder.Append("        services.").Append(methodName).Append('<').Append(serviceType).Append(", ").Append(implementationType).AppendLine(">();");
        }
    }

    private static string GetHandlerServiceType(RequestDescriptor request, HandlerDescriptor handler)
    {
        return handler.Kind switch
        {
            HandlerKind.Request => $"global::SharedKernel.Mediator.IRequestHandler<{request.MetadataName}, {request.Response.MetadataName}>",
            HandlerKind.Command => $"global::SharedKernel.Mediator.ICommandHandler<{request.MetadataName}>",
            HandlerKind.CommandWithResponse => $"global::SharedKernel.Mediator.ICommandHandler<{request.MetadataName}, {request.Response.MetadataName}>",
            HandlerKind.Query => $"global::SharedKernel.Mediator.IQueryHandler<{request.MetadataName}, {request.Response.MetadataName}>",
            _ => throw new ArgumentOutOfRangeException(nameof(handler))
        };
    }
}
