using System.Text;

namespace SharedKernel.Mediator.SourceGenerator;

/// <summary>
/// Emits the generated request pipeline helper owned by the consumer compilation.
/// </summary>
internal static class GeneratedPipelinesEmitter
{
    public static string Emit(DiscoveryModel model)
    {
        var builder = new StringBuilder();
        GeneratedXmlDocumentationEmitter.AppendAutoGeneratedHeader(builder);
        builder.AppendLine("namespace SharedKernel.Mediator;");
        builder.AppendLine();
        builder.AppendLine("internal static class GeneratedPipelines");
        builder.AppendLine("{");

        for (var index = 0; index < model.Requests.Length; index++)
        {
            EmitPipelineMethod(builder, model.Requests[index], index);
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void EmitPipelineMethod(StringBuilder builder, RequestDescriptor request, int index)
    {
        var accessibleHandlers = request.Handlers
            .Where(static handler => handler.IsAccessibleToGeneratedMediator && handler.HasCompatibleHandleMethod)
            .ToArray();

        if (request.Pipelines.Length == 0 || accessibleHandlers.Length != 1)
        {
            return;
        }

        builder.AppendLine();
        builder.Append("    public static global::System.Threading.Tasks.ValueTask<")
            .Append(request.Response.MetadataName)
            .Append("> Invoke_")
            .Append(index.ToString("D4", global::System.Globalization.CultureInfo.InvariantCulture))
            .Append("(AppMediator mediator, ")
            .Append(request.MetadataName)
            .AppendLine(" request,");
        builder.AppendLine("        global::System.Threading.CancellationToken ct)");
        builder.AppendLine("    {");

        for (var pipelineIndex = 0; pipelineIndex < request.Pipelines.Length; pipelineIndex++)
        {
            builder.Append("        var pipeline")
                .Append(pipelineIndex.ToString(global::System.Globalization.CultureInfo.InvariantCulture))
                .Append(" = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<")
                .Append(request.Pipelines[pipelineIndex].MetadataName)
                .AppendLine(">(mediator.Services);");
        }

        builder.Append("        var handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<")
            .Append(accessibleHandlers[0].MetadataName)
            .AppendLine(">(mediator.Services);");
        builder.AppendLine();
        builder.Append("        return ")
            .Append(BuildPipelineInvocation(request, 0))
            .AppendLine(";");
        builder.AppendLine("    }");
    }

    private static string BuildPipelineInvocation(RequestDescriptor request, int pipelineIndex)
    {
        if (pipelineIndex >= request.Pipelines.Length)
        {
            return "handler.Handle(request, ct)";
        }

        return $"pipeline{pipelineIndex}.Handle(request, () => {BuildPipelineInvocation(request, pipelineIndex + 1)}, ct)";
    }
}
