using System.Collections.Immutable;

namespace SharedKernel.Mediator.SourceGenerator;

/// <summary>
/// Emits the generated request pipeline helper owned by the consumer compilation.
/// </summary>
internal static class GeneratedPipelinesEmitter
{
    public static string Emit(DiscoveryModel model)
    {
        var writer = new IndentedCodeWriter();
        GeneratedXmlDocumentationEmitter.AppendAutoGeneratedHeader(writer);
        writer.Line("namespace SharedKernel.Mediator;");
        writer.Line();
        writer.Line("internal static class GeneratedPipelines");
        writer.Line("{");
        writer.Indent();

        for (var index = 0; index < model.Requests.Length; index++)
        {
            var request = model.Requests[index];
            var accessibleHandlers = request.Handlers
                .Where(static handler => handler.IsAccessibleToGeneratedMediator && handler.HasCompatibleHandleMethod)
                .ToArray();

            if (request.Pipelines.Length == 0 || accessibleHandlers.Length != 1)
            {
                continue;
            }

            EmitPipelineMethod(
                writer,
                request.MetadataName,
                request.Response.MetadataName,
                request.Pipelines,
                accessibleHandlers[0].MetadataName,
                index,
                isStream: false);
        }

        for (var index = 0; index < model.StreamRequests.Length; index++)
        {
            var request = model.StreamRequests[index];
            var accessibleHandlers = request.Handlers
                .Where(static handler => handler.IsAccessibleToGeneratedMediator)
                .ToArray();

            if (request.Pipelines.Length == 0 || accessibleHandlers.Length != 1)
            {
                continue;
            }

            EmitPipelineMethod(
                writer,
                request.MetadataName,
                request.ItemResponse.MetadataName,
                request.Pipelines,
                accessibleHandlers[0].MetadataName,
                index,
                isStream: true);
        }

        writer.Unindent();
        writer.Line("}");
        return writer.ToString();
    }

    private static void EmitPipelineMethod(
        IndentedCodeWriter writer,
        string requestMetadataName,
        string responseMetadataName,
        ImmutableArray<PipelineDescriptor> pipelines,
        string handlerMetadataName,
        int index,
        bool isStream)
    {
        writer.Line();
        writer.Line($"public static {GetReturnType(isStream, responseMetadataName)} {GetMethodName(isStream, index)}(AppMediator mediator, {requestMetadataName} request,");
        writer.Line("    global::System.Threading.CancellationToken ct)");
        writer.Line("{");
        writer.Indent();

        for (var pipelineIndex = 0; pipelineIndex < pipelines.Length; pipelineIndex++)
        {
            writer.Line($"var pipeline{pipelineIndex.ToString(global::System.Globalization.CultureInfo.InvariantCulture)} = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{pipelines[pipelineIndex].MetadataName}>(mediator.Services);");
        }

        writer.Line($"var handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{handlerMetadataName}>(mediator.Services);");
        writer.Line();
        writer.Line($"return {BuildPipelineInvocation(pipelines, "handler.Handle(request, ct)")};");
        writer.Unindent();
        writer.Line("}");
    }

    private static string BuildPipelineInvocation(
        ImmutableArray<PipelineDescriptor> pipelines,
        string handlerCall,
        int index = 0)
    {
        return index >= pipelines.Length
            ? handlerCall
            : $"pipeline{index}.Handle(request, () => {BuildPipelineInvocation(pipelines, handlerCall, index + 1)}, ct)";
    }

    private static string GetMethodName(bool isStream, int index)
    {
        return (isStream ? "InvokeStream_" : "Invoke_")
            + index.ToString("D4", global::System.Globalization.CultureInfo.InvariantCulture);
    }

    private static string GetReturnType(bool isStream, string responseMetadataName)
    {
        return isStream
            ? $"global::System.Collections.Generic.IAsyncEnumerable<{responseMetadataName}>"
            : $"global::System.Threading.Tasks.ValueTask<{responseMetadataName}>";
    }
}
