using System.Text;

namespace SharedKernel.Mediator.SourceGenerator;

/// <summary>
/// Emits the generated dispatch helper owned by the consumer compilation.
/// </summary>
internal static class GeneratedDispatchEmitter
{
    public static string Emit(DiscoveryModel model)
    {
        var builder = new StringBuilder();
        var requestList = model.Requests.ToArray();
        var notificationList = model.Notifications.ToArray();
        var streamRequestList = model.StreamRequests.ToArray();

        GeneratedXmlDocumentationEmitter.AppendAutoGeneratedHeader(builder);
        builder.AppendLine("namespace SharedKernel.Mediator;");
        builder.AppendLine();
        builder.AppendLine("internal static class GeneratedDispatch");
        builder.AppendLine("{");
        builder.AppendLine("    public static global::System.Threading.Tasks.ValueTask<TResponse> Send<TResponse>(");
        builder.AppendLine("        AppMediator mediator,");
        builder.AppendLine("        global::SharedKernel.Mediator.IRequest<TResponse> request,");
        builder.AppendLine("        global::System.Threading.CancellationToken ct)");
        builder.AppendLine("    {");
        builder.AppendLine("        return request switch");
        builder.AppendLine("        {");

        foreach (var request in requestList)
        {
            builder.Append("            ")
                .Append(request.MetadataName)
                .Append(" typed => Cast<")
                .Append(request.Response.MetadataName)
                .Append(", TResponse>(mediator.Send(typed, ct)),")
                .AppendLine();
        }

        builder.AppendLine("            _ => ThrowNoHandler<TResponse>(request),");
        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public static global::System.Threading.Tasks.ValueTask<object?> SendObject(");
        builder.AppendLine("        AppMediator mediator,");
        builder.AppendLine("        object request,");
        builder.AppendLine("        global::System.Threading.CancellationToken ct)");
        builder.AppendLine("    {");
        builder.AppendLine("        return request switch");
        builder.AppendLine("        {");

        foreach (var request in requestList)
        {
            builder.Append("            ")
                .Append(request.MetadataName)
                .Append(" typed => Box<")
                .Append(request.Response.MetadataName)
                .Append(">(mediator.Send(typed, ct)),")
                .AppendLine();
        }

        builder.AppendLine("            _ => ThrowUnknownRequestObject(request),");
        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public static global::System.Collections.Generic.IAsyncEnumerable<TResponse> CreateStream<TResponse>(");
        builder.AppendLine("        AppMediator mediator,");
        builder.AppendLine("        global::SharedKernel.Mediator.IStreamRequest<TResponse> request,");
        builder.AppendLine("        global::System.Threading.CancellationToken ct)");
        builder.AppendLine("    {");
        builder.AppendLine("        return request switch");
        builder.AppendLine("        {");

        foreach (var streamRequest in streamRequestList)
        {
            builder.Append("            ")
                .Append(streamRequest.MetadataName)
                .Append(" typed => CastStream<")
                .Append(streamRequest.ItemResponse.MetadataName)
                .Append(", TResponse>(mediator.CreateStream(typed, ct), ct),")
                .AppendLine();
        }

        builder.AppendLine("            _ => ThrowNoStreamHandler<TResponse>(request),");
        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public static global::System.Threading.Tasks.ValueTask Publish<TNotification>(");
        builder.AppendLine("        AppMediator mediator,");
        builder.AppendLine("        TNotification notification,");
        builder.AppendLine("        global::System.Threading.CancellationToken ct)");
        builder.AppendLine("        where TNotification : global::SharedKernel.Mediator.INotification");
        builder.AppendLine("    {");
        builder.AppendLine("        return notification switch");
        builder.AppendLine("        {");

        for (var notificationIndex = 0; notificationIndex < notificationList.Length; notificationIndex++)
        {
            builder.Append("            ")
                .Append(notificationList[notificationIndex].MetadataName)
                .Append(" typed => Publish_")
                .Append(notificationIndex.ToString("D4", global::System.Globalization.CultureInfo.InvariantCulture))
                .Append("(mediator.Services, typed, ct),")
                .AppendLine();
        }

        builder.AppendLine("            _ => global::System.Threading.Tasks.ValueTask.CompletedTask,");
        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine();

        for (var notificationIndex = 0; notificationIndex < notificationList.Length; notificationIndex++)
        {
            EmitNotificationDispatchMethod(builder, notificationList[notificationIndex], notificationIndex);
        }

        builder.AppendLine("    public static async global::System.Threading.Tasks.ValueTask<TTarget> Cast<TSource, TTarget>(");
        builder.AppendLine("        global::System.Threading.Tasks.ValueTask<TSource> source)");
        builder.AppendLine("    {");
        builder.AppendLine("        var result = await source.ConfigureAwait(false);");
        builder.AppendLine();
        builder.AppendLine("        if (result is TTarget typed)");
        builder.AppendLine("        {");
        builder.AppendLine("            return typed;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        return ThrowInvalidResponseCast<TSource, TTarget>();");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public static async global::System.Threading.Tasks.ValueTask<object?> Box<TSource>(");
        builder.AppendLine("        global::System.Threading.Tasks.ValueTask<TSource> source)");
        builder.AppendLine("    {");
        builder.AppendLine("        return await source.ConfigureAwait(false);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public static global::System.Threading.Tasks.ValueTask<TResponse> ThrowNoHandler<TResponse>(");
        builder.AppendLine("        global::SharedKernel.Mediator.IRequest<TResponse> request)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(request);");
        builder.AppendLine();
        builder.AppendLine("        throw new global::System.NotSupportedException($\"Generated request dispatch is not available for request type '{request.GetType().FullName}'.\");");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public static global::System.Threading.Tasks.ValueTask<object?> ThrowUnknownRequestObject(");
        builder.AppendLine("        object request)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(request);");
        builder.AppendLine();
        builder.AppendLine("        throw new global::System.NotSupportedException($\"Generated object dispatch is not available for request type '{request.GetType().FullName}'.\");");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public static global::System.Collections.Generic.IAsyncEnumerable<TResponse> ThrowNoStreamHandler<TResponse>(");
        builder.AppendLine("        global::SharedKernel.Mediator.IStreamRequest<TResponse> request)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(request);");
        builder.AppendLine();
        builder.AppendLine("        return new ThrowingAsyncEnumerable<TResponse>(new global::System.NotSupportedException($\"Generated stream dispatch is not available for request type '{request.GetType().FullName}'.\"));");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public static global::System.Collections.Generic.IAsyncEnumerable<TResponse> ThrowAmbiguousStreamHandlers<TResponse>(");
        builder.AppendLine("        global::SharedKernel.Mediator.IStreamRequest<TResponse> request,");
        builder.AppendLine("        int handlerCount)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(request);");
        builder.AppendLine();
        builder.AppendLine("        return new ThrowingAsyncEnumerable<TResponse>(new global::System.InvalidOperationException($\"Generated stream dispatch found {handlerCount} accessible handlers for request type '{request.GetType().FullName}'.\"));");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public static async global::System.Collections.Generic.IAsyncEnumerable<TTarget> CastStream<TSource, TTarget>(");
        builder.AppendLine("        global::System.Collections.Generic.IAsyncEnumerable<TSource> source,");
        builder.AppendLine("        [global::System.Runtime.CompilerServices.EnumeratorCancellation] global::System.Threading.CancellationToken ct)");
        builder.AppendLine("    {");
        builder.AppendLine("        var enumerator = source.GetAsyncEnumerator(ct);");
        builder.AppendLine("        try");
        builder.AppendLine("        {");
        builder.AppendLine("            while (await enumerator.MoveNextAsync().ConfigureAwait(false))");
        builder.AppendLine("            {");
        builder.AppendLine("                var item = enumerator.Current;");
        builder.AppendLine("                if (item is TTarget typed)");
        builder.AppendLine("                {");
        builder.AppendLine("                    yield return typed;");
        builder.AppendLine("                    continue;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                ThrowInvalidResponseCast<TSource, TTarget>();");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine("        finally");
        builder.AppendLine("        {");
        builder.AppendLine("            await enumerator.DisposeAsync().ConfigureAwait(false);");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public static global::System.Threading.Tasks.ValueTask<TResponse> ThrowAmbiguousHandlers<TResponse>(");
        builder.AppendLine("        global::SharedKernel.Mediator.IRequest<TResponse> request,");
        builder.AppendLine("        int handlerCount)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(request);");
        builder.AppendLine();
        builder.AppendLine("        throw new global::System.InvalidOperationException($\"Generated request dispatch found {handlerCount} accessible handlers for request type '{request.GetType().FullName}'.\");");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public static TTarget ThrowInvalidResponseCast<TSource, TTarget>()");
        builder.AppendLine("    {");
        builder.AppendLine("        throw new global::System.InvalidOperationException($\"Generated request dispatch returned '{typeof(TSource).FullName}' when '{typeof(TTarget).FullName}' was expected.\");");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private sealed class ThrowingAsyncEnumerable<T>(global::System.Exception exception) : global::System.Collections.Generic.IAsyncEnumerable<T>, global::System.Collections.Generic.IAsyncEnumerator<T>");
        builder.AppendLine("    {");
        builder.AppendLine("        public T Current => throw exception;");
        builder.AppendLine();
        builder.AppendLine("        public global::System.Threading.Tasks.ValueTask DisposeAsync()");
        builder.AppendLine("        {");
        builder.AppendLine("            return global::System.Threading.Tasks.ValueTask.CompletedTask;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public global::System.Collections.Generic.IAsyncEnumerator<T> GetAsyncEnumerator(global::System.Threading.CancellationToken cancellationToken = default)");
        builder.AppendLine("        {");
        builder.AppendLine("            return this;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public global::System.Threading.Tasks.ValueTask<bool> MoveNextAsync()");
        builder.AppendLine("        {");
        builder.AppendLine("            return global::System.Threading.Tasks.ValueTask.FromException<bool>(exception);");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static void EmitNotificationDispatchMethod(
        StringBuilder builder,
        NotificationDescriptor notification,
        int notificationIndex)
    {
        var accessibleHandlers = notification.Handlers
            .Where(static handler => handler.IsAccessibleToGeneratedMediator)
            .ToArray();

        builder.Append("    private static ");
        if (accessibleHandlers.Length > 1)
        {
            builder.Append("async ");
        }

        builder.AppendLine("global::System.Threading.Tasks.ValueTask Publish_"
            + notificationIndex.ToString("D4", global::System.Globalization.CultureInfo.InvariantCulture) + "(");
        builder.AppendLine("        global::System.IServiceProvider services,");
        builder.Append("        ")
            .Append(notification.MetadataName)
            .AppendLine(" notification,");
        builder.AppendLine("        global::System.Threading.CancellationToken ct)");
        builder.AppendLine("    {");

        switch (accessibleHandlers.Length)
        {
            case 0:
                builder.AppendLine("        return global::System.Threading.Tasks.ValueTask.CompletedTask;");
                break;
            case 1:
                builder.Append("        return global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<")
                    .Append(accessibleHandlers[0].MetadataName)
                    .AppendLine(">(services).Handle(notification, ct);");
                break;
            default:
                if (notification.PublishInParallel)
                {
                    for (var handlerIndex = 0; handlerIndex < accessibleHandlers.Length; handlerIndex++)
                    {
                        builder.Append("        var handler")
                            .Append(handlerIndex.ToString(global::System.Globalization.CultureInfo.InvariantCulture))
                            .Append(" = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<")
                            .Append(accessibleHandlers[handlerIndex].MetadataName)
                            .AppendLine(">(services).Handle(notification, ct);");
                    }

                    builder.Append("        await global::System.Threading.Tasks.Task.WhenAll(");
                    for (var handlerIndex = 0; handlerIndex < accessibleHandlers.Length; handlerIndex++)
                    {
                        if (handlerIndex > 0)
                        {
                            builder.Append(", ");
                        }

                        builder.Append("handler")
                            .Append(handlerIndex.ToString(global::System.Globalization.CultureInfo.InvariantCulture))
                            .Append(".AsTask()");
                    }

                    builder.AppendLine(").ConfigureAwait(false);");
                }
                else
                {
                    foreach (var handler in accessibleHandlers)
                    {
                        builder.Append("        await global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<")
                            .Append(handler.MetadataName)
                            .AppendLine(">(services).Handle(notification, ct).ConfigureAwait(false);");
                    }
                }

                break;
        }

        builder.AppendLine("    }");
        builder.AppendLine();
    }
}
