using System.Text;

namespace SharedKernel.Mediator.SourceGenerator;

/// <summary>
/// Emits common XML documentation blocks for generated source.
/// </summary>
internal static class GeneratedXmlDocumentationEmitter
{
    public static void AppendAutoGeneratedHeader(StringBuilder builder)
    {
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine();
    }

    public static void AppendSummary(StringBuilder builder, string indentation, params string[] lines)
    {
        builder.Append(indentation).AppendLine("/// <summary>");

        foreach (var line in lines)
        {
            builder.Append(indentation).Append("/// ").AppendLine(line);
        }

        builder.Append(indentation).AppendLine("/// </summary>");
    }

    public static void AppendTypeParam(StringBuilder builder, string indentation, string name, string description)
    {
        builder.Append(indentation)
            .Append("/// <typeparam name=\"")
            .Append(name)
            .Append("\">")
            .Append(description)
            .AppendLine("</typeparam>");
    }

    public static void AppendParam(StringBuilder builder, string indentation, string name, string description)
    {
        builder.Append(indentation)
            .Append("/// <param name=\"")
            .Append(name)
            .Append("\">")
            .Append(description)
            .AppendLine("</param>");
    }

    public static void AppendReturns(StringBuilder builder, string indentation, string description)
    {
        builder.Append(indentation).Append("/// <returns>").Append(description).AppendLine("</returns>");
    }

    public static void AppendInheritdoc(StringBuilder builder, string indentation)
    {
        builder.Append(indentation).AppendLine("/// <inheritdoc />");
    }
}
