exporters:
  otlp/aspire:
    endpoint: ${env:ASPIRE_ENDPOINT}
    headers:
      x-otlp-api-key: ${env:ASPIRE_API_KEY}
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  otlphttp/loki:
    endpoint: http://loki:3100/otlp
  prometheus:
    endpoint: 0.0.0.0:8889

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, transform/sanitize_resources, transform/sanitize_traces, filter/drop_span_events, batch]
      exporters: [otlp/aspire, otlp/tempo]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, transform/sanitize_resources, batch]
      exporters: [otlp/aspire, otlphttp/loki]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, transform/sanitize_resources, batch]
      exporters: [otlp/aspire, prometheus]
