using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SharedKernel.IntegrationEvents.SourceGenerator;

/// <summary>
/// Generates domain event handlers for attributed integration event mapping methods.
/// </summary>
[Generator]
public sealed class IntegrationEventMappingGenerator : IIncrementalGenerator
{
    private const string AttributeName = "SharedKernel.IntegrationEvents.IntegrationEventMappingAttribute";
    private const string DomainEventInterfaceName = "SharedKernel.Domain.IDomainEvent";
    private const string IntegrationEventInterfaceName = "SharedKernel.IntegrationEvents.IIntegrationEvent";

    private static readonly SymbolDisplayFormat FullyQualifiedFormat = new(
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var mappings = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeName,
                static (node, _) => node is MethodDeclarationSyntax,
                static (attributeContext, cancellationToken) => BuildMapping(attributeContext, cancellationToken))
            .Where(static mapping => mapping is not null)
            .Collect()
            .Select(static (mappings, _) => mappings
                .Where(static mapping => mapping is not null)
                .Select(static mapping => mapping!)
                .OrderBy(static mapping => mapping.HandlerTypeName, StringComparer.Ordinal)
                .ToImmutableArray())
            .WithTrackingName("IntegrationEventMappings");

        context.RegisterSourceOutput(mappings, static (productionContext, mappings) =>
        {
            if (mappings.Length == 0)
            {
                return;
            }

            productionContext.AddSource(
                "SharedKernel.IntegrationEvents.GeneratedIntegrationEventMappings.g.cs",
                SourceText.From(Emit(mappings), Encoding.UTF8));
        });
    }

    private static IntegrationEventMappingModel? BuildMapping(
        GeneratorAttributeSyntaxContext context,
        CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        var method = (IMethodSymbol)context.TargetSymbol;
        if (method.IsGenericMethod || !method.IsStatic || method.Parameters.Length != 3)
        {
            return null;
        }

        var domainEvent = method.Parameters[0].Type;
        var integrationEvent = method.ReturnType;
        if (!Implements(domainEvent, DomainEventInterfaceName) || !Implements(integrationEvent, IntegrationEventInterfaceName))
        {
            return null;
        }

        if (method.Parameters[1].Type.ToDisplayString() != "System.Guid" ||
            method.Parameters[2].Type.ToDisplayString() != "System.DateTimeOffset")
        {
            return null;
        }

        var containingType = method.ContainingType.ToDisplayString(FullyQualifiedFormat);
        var domainEventType = domainEvent.ToDisplayString(FullyQualifiedFormat);
        var integrationEventType = integrationEvent.ToDisplayString(FullyQualifiedFormat);
        var handlerTypeName = $"Generated{Sanitize(domainEvent.ToDisplayString())}To{Sanitize(integrationEvent.ToDisplayString())}Handler";

        return new IntegrationEventMappingModel(
            containingType,
            method.Name,
            domainEventType,
            integrationEventType,
            handlerTypeName);
    }

    private static bool Implements(ITypeSymbol type, string interfaceName)
    {
        return string.Equals(type.OriginalDefinition.ToDisplayString(), interfaceName, StringComparison.Ordinal) ||
            type.AllInterfaces.Any(interfaceType =>
            string.Equals(interfaceType.OriginalDefinition.ToDisplayString(), interfaceName, StringComparison.Ordinal));
    }

    private static string Emit(ImmutableArray<IntegrationEventMappingModel> mappings)
    {
        var builder = new StringBuilder(
            """
            // <auto-generated />
            #nullable enable

            namespace SharedKernel.IntegrationEvents.Generated
            {

            """);

        foreach (var mapping in mappings)
        {
            builder.AppendLine($$"""
                internal sealed class {{mapping.HandlerTypeName}}(
                    global::SharedKernel.IntegrationEvents.IIntegrationEventOutbox outbox,
                    global::System.TimeProvider timeProvider)
                    : global::SharedKernel.DomainEvents.IDomainEventHandler<{{mapping.DomainEventType}}>
                {
                    public global::System.Threading.Tasks.ValueTask Handle({{mapping.DomainEventType}} domainEvent, global::System.Threading.CancellationToken ct)
                    {
                        global::System.ArgumentNullException.ThrowIfNull(domainEvent);

                        return outbox.Enqueue(
                            {{mapping.ContainingType}}.{{mapping.MethodName}}(
                                domainEvent,
                                global::System.Guid.CreateVersion7(),
                                timeProvider.GetUtcNow()),
                            ct);
                    }
                }

                """);
        }

        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("namespace Microsoft.Extensions.DependencyInjection");
        builder.AppendLine("{");
        builder.AppendLine();
        builder.AppendLine("internal static class GeneratedIntegrationEventMappingsServiceCollectionExtensions");
        builder.AppendLine("{");
        builder.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedIntegrationEventMappings(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(services);");
        builder.AppendLine("        services.AddSingleton(global::System.TimeProvider.System);");

        foreach (var mapping in mappings)
        {
            builder.AppendLine($"        services.AddScoped<global::SharedKernel.DomainEvents.IDomainEventHandler<{mapping.DomainEventType}>, global::SharedKernel.IntegrationEvents.Generated.{mapping.HandlerTypeName}>();");
        }

        builder.AppendLine("        return services;");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static string Sanitize(string value)
    {
        var builder = new StringBuilder();
        foreach (var character in value.Where(char.IsLetterOrDigit))
        {
            builder.Append(character);
        }

        return builder.ToString();
    }
}

internal sealed class IntegrationEventMappingModel(
    string containingType,
    string methodName,
    string domainEventType,
    string integrationEventType,
    string handlerTypeName)
{
    public string ContainingType { get; } = containingType;

    public string MethodName { get; } = methodName;

    public string DomainEventType { get; } = domainEventType;

    public string IntegrationEventType { get; } = integrationEventType;

    public string HandlerTypeName { get; } = handlerTypeName;
}
