<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>SharedKernel.AspNetCore.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="xunit.v3.mtp-v2" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="SharedKernel.Testing.Assertions" />
        <Using Include="SharedKernel.Testing.AspNetCore" />
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.AspNetCore\SharedKernel.AspNetCore.csproj" />
        <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.Testing\SharedKernel.Testing.csproj" />
        <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.Testing.Assertions\SharedKernel.Testing.Assertions.csproj" />
        <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.Testing.AspNetCore\SharedKernel.Testing.AspNetCore.csproj" />
    </ItemGroup>

</Project>
