<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>SharedKernel.Results.AspNet</PackageId>
        <Description>ASP.NET Core adapters for SharedKernel.Results.</Description>
        <RootNamespace>SharedKernel.Results.AspNet</RootNamespace>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/danigutsch/ViajantesTurismo</RepositoryUrl>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <PackageTags>results;shared-kernel;aspnetcore;http</PackageTags>
    </PropertyGroup>

    <ItemGroup>
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <ProjectReference Include="..\SharedKernel.Results\SharedKernel.Results.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
