// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ViajantesTurismo.Management.Security;

#nullable disable

namespace ViajantesTurismo.Management.Security.Migrations
{
    [DbContext(typeof(ManagementSecurityDbContext))]
    [Migration("20260714160453_InitialManagementSecurity")]
    partial class InitialManagementSecurity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("data_protection_keys", "security");
                });

            modelBuilder.Entity("ViajantesTurismo.Management.Security.ManagementCookieTicketCacheEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(449)
                        .HasColumnType("character varying(449)")
                        .HasColumnName("id")
                        .UseCollation("C");

                    b.Property<DateTimeOffset?>("AbsoluteExpiration")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("absoluteexpiration");

                    b.Property<DateTimeOffset>("ExpiresAtTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiresattime");

                    b.Property<long?>("SlidingExpirationInSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("slidingexpirationinseconds");

                    b.Property<byte[]>("Value")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtTime")
                        .HasDatabaseName("ix_expiresattime");

                    b.ToTable("management_cookie_tickets", "security");
                });
#pragma warning restore 612, 618
        }
    }
}
